// Categorias-padrao do CHECK LIST - MANUTENCAO PREDIAL do setor Manutencao.
// Gerado a partir do roteiro de inspecao enviado pelo salao. Os itens nascem
// com periodo MENSAL (inspecao de rotina) - da para mudar item a item no Editar,
// alem de adicionar/excluir categorias e itens. Vive na chave 'checklist_manutencao',
// separado do check list diario do salao.

export interface CatManutencao { nome: string; itens: { texto: string; freq?: string }[] }

export const CHECKLIST_MANUTENCAO: CatManutencao[] = [
  {
    nome: 'ESTRUTURA FÍSICA / PREDIAL',
    itens: [
      { texto: 'Paredes — rachaduras', freq: 'Mensal' },
      { texto: 'Paredes — trincas', freq: 'Mensal' },
      { texto: 'Paredes — infiltrações', freq: 'Mensal' },
      { texto: 'Paredes — umidade', freq: 'Mensal' },
      { texto: 'Paredes — descascamento da pintura', freq: 'Mensal' },
      { texto: 'Paredes — mofo', freq: 'Mensal' },
      { texto: 'Paredes — revestimentos soltos', freq: 'Mensal' },
      { texto: 'Paredes — azulejos quebrados', freq: 'Mensal' },
      { texto: 'Paredes — azulejos soltos', freq: 'Mensal' },
      { texto: 'Paredes — rejuntes deteriorados', freq: 'Mensal' },
      { texto: 'Paredes — acabamento das paredes', freq: 'Mensal' },
      { texto: 'Paredes — quinas e cantos danificados', freq: 'Mensal' },
      { texto: 'Tetos / forros — manchas de infiltração', freq: 'Mensal' },
      { texto: 'Tetos / forros — placas de forro', freq: 'Mensal' },
      { texto: 'Tetos / forros — forro solto', freq: 'Mensal' },
      { texto: 'Tetos / forros — rachaduras', freq: 'Mensal' },
      { texto: 'Tetos / forros — pintura', freq: 'Mensal' },
      { texto: 'Tetos / forros — sinais de vazamento', freq: 'Mensal' },
      { texto: 'Tetos / forros — pontos próximos a luminárias', freq: 'Mensal' },
      { texto: 'Tetos / forros — estruturas aparentes', freq: 'Mensal' },
      { texto: 'Pisos — peças quebradas', freq: 'Mensal' },
      { texto: 'Pisos — peças soltas', freq: 'Mensal' },
      { texto: 'Pisos — desníveis', freq: 'Mensal' },
      { texto: 'Pisos — rachaduras', freq: 'Mensal' },
      { texto: 'Pisos — rejuntes', freq: 'Mensal' },
      { texto: 'Pisos — pisos escorregadios', freq: 'Mensal' },
      { texto: 'Pisos — rodapés', freq: 'Mensal' },
      { texto: 'Pisos — acabamento', freq: 'Mensal' },
      { texto: 'Pisos — risco de tropeço', freq: 'Mensal' },
    ],
  },
  {
    nome: 'PORTAS, JANELAS E VIDROS',
    itens: [
      { texto: 'Portas — Abrindo corretamente', freq: 'Mensal' },
      { texto: 'Portas — Fechando corretamente', freq: 'Mensal' },
      { texto: 'Portas — Dobradiças funcionando', freq: 'Mensal' },
      { texto: 'Portas — Fechaduras funcionando', freq: 'Mensal' },
      { texto: 'Portas — Maçanetas firmes', freq: 'Mensal' },
      { texto: 'Portas — Batentes íntegros', freq: 'Mensal' },
      { texto: 'Portas — Mola aérea funcionando, quando houver', freq: 'Mensal' },
      { texto: 'Portas — Amortecedor funcionando', freq: 'Mensal' },
      { texto: 'Portas — Porta sem empenamento', freq: 'Mensal' },
      { texto: 'Portas — Porta sem ruídos anormais', freq: 'Mensal' },
      { texto: 'Janelas — Abertura funcionando', freq: 'Mensal' },
      { texto: 'Janelas — Fechamento funcionando', freq: 'Mensal' },
      { texto: 'Janelas — Travas funcionando', freq: 'Mensal' },
      { texto: 'Janelas — Trilhos funcionando', freq: 'Mensal' },
      { texto: 'Janelas — Vidros íntegros', freq: 'Mensal' },
      { texto: 'Janelas — Vedação adequada', freq: 'Mensal' },
      { texto: 'Janelas — Sem infiltração', freq: 'Mensal' },
      { texto: 'Vidros / espelhos — Espelhos sem trincas', freq: 'Mensal' },
      { texto: 'Vidros / espelhos — Espelhos firmes', freq: 'Mensal' },
      { texto: 'Vidros / espelhos — Fixações seguras', freq: 'Mensal' },
      { texto: 'Vidros / espelhos — Vidros sem trincas', freq: 'Mensal' },
      { texto: 'Vidros / espelhos — Películas íntegras', freq: 'Mensal' },
      { texto: 'Vidros / espelhos — Estrutura de sustentação adequada', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ELÉTRICA E ILUMINAÇÃO',
    itens: [
      { texto: 'Instalação elétrica — Tomadas funcionando', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Interruptores funcionando', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Espelhos das tomadas íntegros', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Tomadas sem aquecimento anormal', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Tomadas sem faíscas', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Cabos sem exposição', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Fiação sem danos aparentes', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Quadros elétricos identificados', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Disjuntores identificados', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Quadro sem sinais de aquecimento', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Quadro sem cheiro de queimado', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Circuitos identificados', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Dispositivos de proteção adequados e em condição de uso', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Extensões verificadas', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Filtros de linha verificados', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Cabos organizados', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Sem sobrecarga de tomadas', freq: 'Mensal' },
      { texto: 'Instalação elétrica — Equipamentos ligados em pontos adequados', freq: 'Mensal' },
      { texto: 'Iluminação — Lâmpadas funcionando', freq: 'Mensal' },
      { texto: 'Iluminação — Luminárias funcionando', freq: 'Mensal' },
      { texto: 'Iluminação — Spots funcionando', freq: 'Mensal' },
      { texto: 'Iluminação — Pendentes funcionando', freq: 'Mensal' },
      { texto: 'Iluminação — Fitas LED funcionando', freq: 'Mensal' },
      { texto: 'Iluminação — Iluminação dos espelhos funcionando', freq: 'Mensal' },
      { texto: 'Iluminação — Iluminação da recepção funcionando', freq: 'Mensal' },
      { texto: 'Iluminação — Iluminação dos lavatórios funcionando', freq: 'Mensal' },
      { texto: 'Iluminação — Iluminação dos banheiros funcionando', freq: 'Mensal' },
      { texto: 'Iluminação — Iluminação externa funcionando', freq: 'Mensal' },
      { texto: 'Iluminação — Fachada iluminada', freq: 'Mensal' },
      { texto: 'Iluminação — Letreiro iluminado', freq: 'Mensal' },
      { texto: 'Iluminação — Sensores funcionando, quando houver', freq: 'Mensal' },
      { texto: 'Iluminação — Temporizadores funcionando, quando houver', freq: 'Mensal' },
      { texto: 'Iluminação — Luminárias firmes', freq: 'Mensal' },
      { texto: 'Iluminação — Sem fios aparentes', freq: 'Mensal' },
    ],
  },
  {
    nome: 'HIDRÁULICA, ESGOTO E DRENAGEM',
    itens: [
      { texto: 'Hidráulica — Água — Torneiras funcionando', freq: 'Mensal' },
      { texto: 'Hidráulica — Água — Registros funcionando', freq: 'Mensal' },
      { texto: 'Hidráulica — Água — Pressão adequada', freq: 'Mensal' },
      { texto: 'Hidráulica — Água — Sem vazamentos', freq: 'Mensal' },
      { texto: 'Hidráulica — Água — Mangueiras em bom estado', freq: 'Mensal' },
      { texto: 'Hidráulica — Água — Conexões sem vazamento', freq: 'Mensal' },
      { texto: 'Hidráulica — Água — Tubulações sem vazamento aparente', freq: 'Mensal' },
      { texto: 'Hidráulica — Lavatórios — Torneira funcionando', freq: 'Mensal' },
      { texto: 'Hidráulica — Lavatórios — Registro funcionando', freq: 'Mensal' },
      { texto: 'Hidráulica — Lavatórios — Cuba íntegra', freq: 'Mensal' },
      { texto: 'Hidráulica — Lavatórios — Ralo funcionando', freq: 'Mensal' },
      { texto: 'Hidráulica — Lavatórios — Sifão sem vazamento', freq: 'Mensal' },
      { texto: 'Hidráulica — Lavatórios — Mangueira de ducha funcionando', freq: 'Mensal' },
      { texto: 'Hidráulica — Lavatórios — Ducha funcionando', freq: 'Mensal' },
      { texto: 'Hidráulica — Lavatórios — Suporte da ducha firme', freq: 'Mensal' },
      { texto: 'Hidráulica — Lavatórios — Água quente funcionando, quando houver', freq: 'Mensal' },
      { texto: 'Hidráulica — Lavatórios — Misturador funcionando', freq: 'Mensal' },
      { texto: 'Hidráulica — Banheiros — Torneira', freq: 'Mensal' },
      { texto: 'Hidráulica — Banheiros — Descarga', freq: 'Mensal' },
      { texto: 'Hidráulica — Banheiros — Vaso sanitário', freq: 'Mensal' },
      { texto: 'Hidráulica — Banheiros — Caixa acoplada', freq: 'Mensal' },
      { texto: 'Hidráulica — Banheiros — Sifão', freq: 'Mensal' },
      { texto: 'Hidráulica — Banheiros — Ralo', freq: 'Mensal' },
      { texto: 'Hidráulica — Banheiros — Registro', freq: 'Mensal' },
      { texto: 'Hidráulica — Banheiros — Chuveiro, se houver', freq: 'Mensal' },
      { texto: 'Hidráulica — Banheiros — Vazamentos', freq: 'Mensal' },
      { texto: 'Hidráulica — Banheiros — Vedação', freq: 'Mensal' },
      { texto: 'Hidráulica — Banheiros — Acessórios fixados', freq: 'Mensal' },
      { texto: 'Esgoto e drenagem — Ralos funcionando', freq: 'Mensal' },
      { texto: 'Esgoto e drenagem — Ralos sem entupimento', freq: 'Mensal' },
      { texto: 'Esgoto e drenagem — Sifões funcionando', freq: 'Mensal' },
      { texto: 'Esgoto e drenagem — Tubulações sem vazamentos', freq: 'Mensal' },
      { texto: 'Esgoto e drenagem — Lavatórios drenando corretamente', freq: 'Mensal' },
      { texto: 'Esgoto e drenagem — Banheiros drenando corretamente', freq: 'Mensal' },
      { texto: 'Esgoto e drenagem — Caixa de gordura, quando aplicável', freq: 'Mensal' },
      { texto: 'Esgoto e drenagem — Grelhas íntegras', freq: 'Mensal' },
      { texto: 'Esgoto e drenagem — Canaletas funcionando', freq: 'Mensal' },
      { texto: 'Esgoto e drenagem — Ausência de retorno de esgoto', freq: 'Mensal' },
      { texto: 'Esgoto e drenagem — Ausência de mau cheiro anormal', freq: 'Mensal' },
      { texto: 'Esgoto e drenagem — Drenos de equipamentos funcionando', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CLIMATIZAÇÃO',
    itens: [
      { texto: 'Ar-condicionado / climatização — Liga', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Desliga', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Resfria adequadamente', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Controle remoto funcionando', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Filtros limpos', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Evaporadora limpa', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Condensadora em condições adequadas', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Dreno desobstruído', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Sem vazamento de água', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Sem ruído anormal', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Sem vibração anormal', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Temperatura adequada', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Tubulação isolada', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Suporte firme', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Instalação elétrica adequada', freq: 'Mensal' },
      { texto: 'Ar-condicionado / climatização — Manutenção preventiva registrada', freq: 'Mensal' },
    ],
  },
  {
    nome: 'SEGURANÇA, INCÊNDIO E EMERGÊNCIA',
    itens: [
      { texto: 'Segurança contra incêndio — Extintores presentes', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Extintores acessíveis', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Extintores sinalizados', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Lacres íntegros', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Manômetros em condição adequada, quando aplicável', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Validade/inspeção controlada', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Sinalização de emergência', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Iluminação de emergência', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Saídas desobstruídas', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Portas de emergência funcionando, quando houver', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Rotas de fuga livres', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Placas de emergência íntegras', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Equipamentos de emergência acessíveis', freq: 'Mensal' },
      { texto: 'Segurança contra incêndio — Documentação aplicável atualizada', freq: 'Mensal' },
      { texto: 'Detecção e alarme — Central de alarme', freq: 'Mensal' },
      { texto: 'Detecção e alarme — Detectores', freq: 'Mensal' },
      { texto: 'Detecção e alarme — Acionadores manuais', freq: 'Mensal' },
      { texto: 'Detecção e alarme — Sirenes', freq: 'Mensal' },
      { texto: 'Detecção e alarme — Sensores', freq: 'Mensal' },
      { texto: 'Detecção e alarme — Bateria', freq: 'Mensal' },
      { texto: 'Detecção e alarme — Cabeamento', freq: 'Mensal' },
      { texto: 'Detecção e alarme — Comunicação do sistema', freq: 'Mensal' },
      { texto: 'Detecção e alarme — Teste periódico registrado', freq: 'Mensal' },
      { texto: 'Equipamentos de emergência — Kit primeiros socorros', freq: 'Mensal' },
      { texto: 'Equipamentos de emergência — Iluminação de emergência', freq: 'Mensal' },
      { texto: 'Equipamentos de emergência — Sinalização', freq: 'Mensal' },
      { texto: 'Equipamentos de emergência — Extintores', freq: 'Mensal' },
      { texto: 'Equipamentos de emergência — Alarmes', freq: 'Mensal' },
      { texto: 'Equipamentos de emergência — Rotas de fuga', freq: 'Mensal' },
      { texto: 'Equipamentos de emergência — Saídas', freq: 'Mensal' },
      { texto: 'Equipamentos de emergência — Equipamentos de emergência', freq: 'Mensal' },
      { texto: 'Equipamentos de emergência — Telefones de emergência disponíveis', freq: 'Mensal' },
    ],
  },
  {
    nome: 'SEGURANÇA ELETRÔNICA, REDE E ACESSO',
    itens: [
      { texto: 'Segurança eletrônica — CFTV — Câmeras funcionando', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — CFTV — Imagens nítidas', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — CFTV — Câmeras posicionadas corretamente', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — CFTV — Gravador funcionando', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — CFTV — Armazenamento funcionando', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — CFTV — Data/hora corretas', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — CFTV — Monitor funcionando', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — CFTV — Acesso ao sistema funcionando', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — Alarme — Central funcionando', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — Alarme — Sensores funcionando', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — Alarme — Sirene funcionando', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — Alarme — Controle remoto funcionando', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — Alarme — Bateria funcionando', freq: 'Mensal' },
      { texto: 'Segurança eletrônica — Alarme — Comunicação funcionando', freq: 'Mensal' },
      { texto: 'Internet / infraestrutura de rede — Roteador funcionando', freq: 'Mensal' },
      { texto: 'Internet / infraestrutura de rede — Modem funcionando', freq: 'Mensal' },
      { texto: 'Internet / infraestrutura de rede — Switch funcionando', freq: 'Mensal' },
      { texto: 'Internet / infraestrutura de rede — Pontos de rede funcionando', freq: 'Mensal' },
      { texto: 'Internet / infraestrutura de rede — Cabos organizados', freq: 'Mensal' },
      { texto: 'Internet / infraestrutura de rede — Cabos sem danos', freq: 'Mensal' },
      { texto: 'Internet / infraestrutura de rede — Rack organizado, quando houver', freq: 'Mensal' },
      { texto: 'Internet / infraestrutura de rede — Equipamentos ventilados', freq: 'Mensal' },
      { texto: 'Internet / infraestrutura de rede — Nobreak funcionando, quando houver', freq: 'Mensal' },
      { texto: 'Internet / infraestrutura de rede — Tomadas do rack funcionando', freq: 'Mensal' },
      { texto: 'Fechaduras e controle de acesso — Fechaduras', freq: 'Mensal' },
      { texto: 'Fechaduras e controle de acesso — Maçanetas', freq: 'Mensal' },
      { texto: 'Fechaduras e controle de acesso — Chaves', freq: 'Mensal' },
      { texto: 'Fechaduras e controle de acesso — Controle eletrônico', freq: 'Mensal' },
      { texto: 'Fechaduras e controle de acesso — Fechaduras digitais', freq: 'Mensal' },
      { texto: 'Fechaduras e controle de acesso — Senhas', freq: 'Mensal' },
      { texto: 'Fechaduras e controle de acesso — Biometria', freq: 'Mensal' },
      { texto: 'Fechaduras e controle de acesso — Leitores', freq: 'Mensal' },
      { texto: 'Fechaduras e controle de acesso — Portões', freq: 'Mensal' },
      { texto: 'Fechaduras e controle de acesso — Interfone', freq: 'Mensal' },
      { texto: 'Fechaduras e controle de acesso — Campainha', freq: 'Mensal' },
    ],
  },
  {
    nome: 'MOBILIÁRIO DO SALÃO',
    itens: [
      { texto: 'Cadeiras de corte — Estrutura firme', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Base firme', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Sistema hidráulico funcionando', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Regulagem funcionando', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Encosto funcionando', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Apoio de braço íntegro', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Estofamento íntegro', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Rodízios funcionando', freq: 'Mensal' },
      { texto: 'Cadeiras de manicure — Estrutura firme', freq: 'Mensal' },
      { texto: 'Cadeiras de manicure — Regulagens funcionando', freq: 'Mensal' },
      { texto: 'Cadeiras de manicure — Rodízios funcionando', freq: 'Mensal' },
      { texto: 'Cadeiras de manicure — Estofamento íntegro', freq: 'Mensal' },
      { texto: 'Poltronas / recepção — Estrutura firme', freq: 'Mensal' },
      { texto: 'Poltronas / recepção — Pés firmes', freq: 'Mensal' },
      { texto: 'Poltronas / recepção — Estofamento', freq: 'Mensal' },
      { texto: 'Poltronas / recepção — Costuras', freq: 'Mensal' },
      { texto: 'Poltronas / recepção — Apoios', freq: 'Mensal' },
      { texto: 'Poltronas / recepção — Rodízios', freq: 'Mensal' },
      { texto: 'Carrinhos auxiliares — Rodas', freq: 'Mensal' },
      { texto: 'Carrinhos auxiliares — Gavetas', freq: 'Mensal' },
      { texto: 'Carrinhos auxiliares — Estrutura', freq: 'Mensal' },
      { texto: 'Carrinhos auxiliares — Bandejas', freq: 'Mensal' },
      { texto: 'Carrinhos auxiliares — Rodízios', freq: 'Mensal' },
      { texto: 'Armários — Portas', freq: 'Mensal' },
      { texto: 'Armários — Dobradiças', freq: 'Mensal' },
      { texto: 'Armários — Fechaduras', freq: 'Mensal' },
      { texto: 'Armários — Gavetas', freq: 'Mensal' },
      { texto: 'Armários — Corrediças', freq: 'Mensal' },
      { texto: 'Armários — Puxadores', freq: 'Mensal' },
      { texto: 'Armários — Estrutura', freq: 'Mensal' },
    ],
  },
  {
    nome: 'EQUIPAMENTOS DE ATENDIMENTO',
    itens: [
      { texto: 'Equipamentos de cabeleireiro — Secadores — Liga', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Secadores — Desliga', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Secadores — Temperaturas funcionando', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Secadores — Velocidades funcionando', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Secadores — Cabo íntegro', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Secadores — Plugue íntegro', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Secadores — Sem aquecimento anormal', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Secadores — Filtro/entrada de ar limpo', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Secadores — Sem ruído anormal', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Pranchas — Liga', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Pranchas — Temperatura funcionando', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Pranchas — Cabo íntegro', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Pranchas — Plugue íntegro', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Pranchas — Placas íntegras', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Pranchas — Controle funcionando', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Pranchas — Sem aquecimento anormal', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Modeladores/Babyliss — Liga', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Modeladores/Babyliss — Temperatura', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Modeladores/Babyliss — Cabo', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Modeladores/Babyliss — Plugue', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Modeladores/Babyliss — Estrutura', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Modeladores/Babyliss — Controle', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Máquinas de corte — Motor', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Máquinas de corte — Lâminas', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Máquinas de corte — Cabo', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Máquinas de corte — Bateria', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Máquinas de corte — Carregador', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Máquinas de corte — Ruído', freq: 'Mensal' },
      { texto: 'Equipamentos de cabeleireiro — Máquinas de corte — Lubrificação conforme fabricante', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Lavatório', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Cuba', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Torneira', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Misturador', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Ducha', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Mangueira', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Sifão', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Dreno', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Aquecedor, quando houver', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Sistema de água quente', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Estrutura da cadeira', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Estofamento', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Regulagem', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Apoio de pescoço', freq: 'Mensal' },
      { texto: 'Equipamentos dos lavatórios — Vedação', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Cadeiras', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Mesas', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Luminárias', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Cabos elétricos', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Lixas elétricas', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Micromotores', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Cabines UV/LED', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Equipamentos de esterilização, conforme estrutura do salão', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Pedilúvios', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Hidromassagem', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Aquecedores', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Sistemas de drenagem', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Apoios', freq: 'Mensal' },
      { texto: 'Equipamentos de manicure / pedicure — Pedaleiras', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Macas', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Carrinhos', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Vaporizadores', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Alta frequência', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Aparelhos de radiofrequência', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Ultrassom', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Equipamentos de limpeza de pele', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Equipamentos de LED', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Outros equipamentos estéticos', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Cabos', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Fontes', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Pedais', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Acessórios', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Manutenção preventiva', freq: 'Mensal' },
      { texto: 'Equipamentos de estética — Registro de manutenção', freq: 'Mensal' },
    ],
  },
  {
    nome: 'LAVANDERIA, LIMPEZA E COPA',
    itens: [
      { texto: 'Lavanderia — Máquina de lavar — Funcionamento', freq: 'Mensal' },
      { texto: 'Lavanderia — Máquina de lavar — Mangueiras', freq: 'Mensal' },
      { texto: 'Lavanderia — Máquina de lavar — Entrada de água', freq: 'Mensal' },
      { texto: 'Lavanderia — Máquina de lavar — Saída de água', freq: 'Mensal' },
      { texto: 'Lavanderia — Máquina de lavar — Drenagem', freq: 'Mensal' },
      { texto: 'Lavanderia — Máquina de lavar — Vazamentos', freq: 'Mensal' },
      { texto: 'Lavanderia — Máquina de lavar — Borracha de vedação', freq: 'Mensal' },
      { texto: 'Lavanderia — Máquina de lavar — Filtro', freq: 'Mensal' },
      { texto: 'Lavanderia — Máquina de lavar — Ruídos', freq: 'Mensal' },
      { texto: 'Lavanderia — Máquina de lavar — Vibração', freq: 'Mensal' },
      { texto: 'Lavanderia — Secadora — Funcionamento', freq: 'Mensal' },
      { texto: 'Lavanderia — Secadora — Filtro', freq: 'Mensal' },
      { texto: 'Lavanderia — Secadora — Ventilação', freq: 'Mensal' },
      { texto: 'Lavanderia — Secadora — Duto', freq: 'Mensal' },
      { texto: 'Lavanderia — Secadora — Cabo', freq: 'Mensal' },
      { texto: 'Lavanderia — Secadora — Plugue', freq: 'Mensal' },
      { texto: 'Lavanderia — Secadora — Aquecimento adequado', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza — Aspirador', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza — Lavadora', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza — Enceradeira, se houver', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza — Extratora, se houver', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza — Vassouras elétricas, se houver', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza — Cabos', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza — Tomadas', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza — Filtros', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza — Mangueiras', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza — Rodas', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza — Reservatórios', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza — Baterias/carregadores', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Geladeira', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Freezer', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Micro-ondas', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Cafeteira', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Purificador', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Filtro de água', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Bebedouro', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Forno', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Armários', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Torneira', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Pia', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Sifão', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Tomadas', freq: 'Mensal' },
      { texto: 'Copa / área de apoio — Instalação elétrica', freq: 'Mensal' },
      { texto: 'Bebedouro / purificador — Funcionamento', freq: 'Mensal' },
      { texto: 'Bebedouro / purificador — Vazamento', freq: 'Mensal' },
      { texto: 'Bebedouro / purificador — Torneira', freq: 'Mensal' },
      { texto: 'Bebedouro / purificador — Mangueira', freq: 'Mensal' },
      { texto: 'Bebedouro / purificador — Filtro', freq: 'Mensal' },
      { texto: 'Bebedouro / purificador — Prazo de troca do filtro', freq: 'Mensal' },
      { texto: 'Bebedouro / purificador — Refrigeração, quando houver', freq: 'Mensal' },
      { texto: 'Bebedouro / purificador — Limpeza técnica', freq: 'Mensal' },
      { texto: 'Bebedouro / purificador — Manutenção registrada', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ÁREA EXTERNA, ELEVADOR E ESTACIONAMENTO',
    itens: [
      { texto: 'Fachada e área externa — Letreiro', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Iluminação da fachada', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Placa', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Revestimento', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Pintura', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Vidros', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Porta de entrada', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Fechadura', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Calçada', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Marquise', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Toldos', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Estruturas externas', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Comunicação visual', freq: 'Mensal' },
      { texto: 'Fachada e área externa — Elementos decorativos externos', freq: 'Mensal' },
      { texto: 'Elevador / plataformas — Funcionamento', freq: 'Mensal' },
      { texto: 'Elevador / plataformas — Portas', freq: 'Mensal' },
      { texto: 'Elevador / plataformas — Botões', freq: 'Mensal' },
      { texto: 'Elevador / plataformas — Iluminação', freq: 'Mensal' },
      { texto: 'Elevador / plataformas — Comunicação', freq: 'Mensal' },
      { texto: 'Elevador / plataformas — Alarmes', freq: 'Mensal' },
      { texto: 'Elevador / plataformas — Manutenção contratada', freq: 'Mensal' },
      { texto: 'Elevador / plataformas — Inspeções obrigatórias', freq: 'Mensal' },
      { texto: 'Elevador / plataformas — Registros de manutenção', freq: 'Mensal' },
      { texto: 'Estacionamento / acesso — Iluminação', freq: 'Mensal' },
      { texto: 'Estacionamento / acesso — Portões', freq: 'Mensal' },
      { texto: 'Estacionamento / acesso — Motor do portão', freq: 'Mensal' },
      { texto: 'Estacionamento / acesso — Controle remoto', freq: 'Mensal' },
      { texto: 'Estacionamento / acesso — Interfone', freq: 'Mensal' },
      { texto: 'Estacionamento / acesso — Câmeras', freq: 'Mensal' },
      { texto: 'Estacionamento / acesso — Sinalização', freq: 'Mensal' },
      { texto: 'Estacionamento / acesso — Piso', freq: 'Mensal' },
      { texto: 'Estacionamento / acesso — Drenagem', freq: 'Mensal' },
      { texto: 'Estacionamento / acesso — Estrutura', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ENERGIA E FERRAMENTAS',
    itens: [
      { texto: 'Nobreak / gerador — Nobreak — Nobreak funcionando', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Nobreak — Bateria', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Nobreak — Autonomia', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Nobreak — Cabos', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Nobreak — Tomadas', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Nobreak — Indicadores', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Nobreak — Teste periódico', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Gerador — Combustível', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Gerador — Bateria', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Gerador — Motor', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Gerador — Cabos', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Gerador — Sistema de acionamento', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Gerador — Teste', freq: 'Mensal' },
      { texto: 'Nobreak / gerador — Gerador — Manutenção preventiva', freq: 'Mensal' },
      { texto: 'Ferramentas da manutenção — Ferramentas identificadas', freq: 'Mensal' },
      { texto: 'Ferramentas da manutenção — Ferramentas organizadas', freq: 'Mensal' },
      { texto: 'Ferramentas da manutenção — Ferramentas em bom estado', freq: 'Mensal' },
      { texto: 'Ferramentas da manutenção — Ferramentas elétricas em bom estado', freq: 'Mensal' },
      { texto: 'Ferramentas da manutenção — Cabos íntegros', freq: 'Mensal' },
      { texto: 'Ferramentas da manutenção — Equipamentos de proteção', freq: 'Mensal' },
      { texto: 'Ferramentas da manutenção — Local de armazenamento adequado', freq: 'Mensal' },
    ],
  },
]
