// Categorias-padrao do CHECK LIST - COORDENACAO (setor Coordenador).
// Gerado a partir do manual de coordenacao enviado pelo salao. Mesmo padrao
// do check list de Manutencao Predial: uma categoria por bloco, subgrupos
// viram prefixo do item. Periodo sugerido por categoria (Diario para a
// operacao do dia, Semanal para rotina, Mensal para gestao) - da para mudar
// item a item no modo Editar. Vive na chave 'checklist_coordenacao'.

export interface CatCoordenacao { nome: string; itens: { texto: string; freq?: string }[] }

export const CHECKLIST_COORDENACAO: CatCoordenacao[] = [
  {
    nome: 'ABERTURA DA OPERAÇÃO — INÍCIO DO DIA',
    itens: [
      { texto: 'Estrutura e ambiente — Verificar se o salão está limpo e organizado.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar limpeza do centro do salão.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar lavatórios.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar bancadas.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar cadeiras de atendimento.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar espelhos.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar vidro da recepção.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar vitrines.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar jardim.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar estofados.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar armários.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar gavetas das manicures.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar gavetas da dosagem.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar carrinhos e rodas.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar iluminação.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar temperatura do ambiente.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar ar-condicionado.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar aroma do salão.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar música ambiente.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar apresentação geral do salão.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar se os dispositivos de papel higiênico estão abastecidos.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar se os dispositivos de papel-toalha estão abastecidos.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar sabonete.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar demais itens de banheiro.', freq: 'Diário' },
      { texto: 'Estrutura e ambiente — Verificar café e estrutura de atendimento.', freq: 'Diário' },
      { texto: 'Equipe — Conferir profissionais escalados para o dia.', freq: 'Diário' },
      { texto: 'Equipe — Conferir possíveis faltas.', freq: 'Diário' },
      { texto: 'Equipe — Conferir atrasos previstos.', freq: 'Diário' },
      { texto: 'Equipe — Verificar se há equipe suficiente para a demanda.', freq: 'Diário' },
      { texto: 'Equipe — Conferir escala.', freq: 'Diário' },
      { texto: 'Equipe — Conferir folgas.', freq: 'Diário' },
      { texto: 'Equipe — Conferir férias, quando aplicável.', freq: 'Diário' },
      { texto: 'Equipe — Conferir necessidade de cobertura.', freq: 'Diário' },
      { texto: 'Equipe — Redistribuir profissionais quando necessário.', freq: 'Diário' },
      { texto: 'Equipe — Comunicar ajustes à equipe.', freq: 'Diário' },
      { texto: 'Equipe — Enviar lembretes necessários.', freq: 'Diário' },
      { texto: 'Equipe — Alinhar informações importantes do dia.', freq: 'Diário' },
      { texto: 'Apresentação pessoal — Conferir vestimentas profissionais.', freq: 'Diário' },
      { texto: 'Apresentação pessoal — Garantir padrão de cores: preto, branco e cinza.', freq: 'Diário' },
      { texto: 'Apresentação pessoal — Conferir apresentação pessoal.', freq: 'Diário' },
      { texto: 'Apresentação pessoal — Conferir postura profissional.', freq: 'Diário' },
      { texto: 'Apresentação pessoal — Conferir uso correto dos EPIs.', freq: 'Diário' },
      { texto: 'Apresentação pessoal — Conferir máscaras.', freq: 'Diário' },
      { texto: 'Apresentação pessoal — Conferir luvas.', freq: 'Diário' },
      { texto: 'Apresentação pessoal — Conferir jalecos.', freq: 'Diário' },
      { texto: 'Apresentação pessoal — Conferir sapatos fechados das manicures.', freq: 'Diário' },
      { texto: 'Apresentação pessoal — Corrigir imediatamente desvios identificados.', freq: 'Diário' },
    ],
  },
  {
    nome: 'CONFERÊNCIA DAS AGENDAS',
    itens: [
      { texto: 'Verificar todos os agendamentos do dia.', freq: 'Diário' },
      { texto: 'Conferir se cada cliente está com o profissional correto.', freq: 'Diário' },
      { texto: 'Conferir horário correto.', freq: 'Diário' },
      { texto: 'Conferir serviço correto.', freq: 'Diário' },
      { texto: 'Identificar cliente agendada com profissional errado.', freq: 'Diário' },
      { texto: 'Identificar cliente sem agendamento.', freq: 'Diário' },
      { texto: 'Conferir possíveis conflitos de horários.', freq: 'Diário' },
      { texto: 'Conferir grandes grupos.', freq: 'Diário' },
      { texto: 'Conferir agendamentos múltiplos.', freq: 'Diário' },
      { texto: 'Organizar atendimentos simultâneos.', freq: 'Diário' },
      { texto: 'Conferir serviços internos.', freq: 'Diário' },
      { texto: 'Verificar noivas.', freq: 'Diário' },
      { texto: 'Verificar clientes especiais.', freq: 'Diário' },
      { texto: 'Verificar atendimentos que exigem maior preparação.', freq: 'Diário' },
      { texto: 'Verificar possíveis encaixes.', freq: 'Diário' },
      { texto: 'Verificar profissionais responsáveis por cada atendimento.', freq: 'Diário' },
      { texto: 'Antecipar possíveis atrasos.', freq: 'Diário' },
      { texto: 'Ajustar agenda quando necessário.', freq: 'Diário' },
      { texto: 'Redistribuir atendimentos quando necessário.', freq: 'Diário' },
      { texto: 'Verificar se algum profissional pretende sair antes do término da agenda.', freq: 'Diário' },
      { texto: 'Garantir que nenhum profissional vá embora deixando cliente agendado sem solução.', freq: 'Diário' },
    ],
  },
  {
    nome: 'ACOMPANHAMENTO DOS PROFISSIONAIS',
    itens: [
      { texto: 'Verificar chegada dos profissionais.', freq: 'Diário' },
      { texto: 'Acompanhar atrasos.', freq: 'Diário' },
      { texto: 'Realizar alinhamento sobre atrasos.', freq: 'Diário' },
      { texto: 'Acompanhar faltas.', freq: 'Diário' },
      { texto: 'Realizar alinhamento sobre faltas.', freq: 'Diário' },
      { texto: 'Verificar comunicação dos profissionais.', freq: 'Diário' },
      { texto: 'Verificar postura.', freq: 'Diário' },
      { texto: 'Verificar qualidade dos procedimentos.', freq: 'Diário' },
      { texto: 'Verificar produtividade.', freq: 'Diário' },
      { texto: 'Verificar organização da estação de trabalho.', freq: 'Diário' },
      { texto: 'Verificar cumprimento dos processos.', freq: 'Diário' },
      { texto: 'Verificar comportamento.', freq: 'Diário' },
      { texto: 'Verificar trabalho em equipe.', freq: 'Diário' },
      { texto: 'Verificar comprometimento.', freq: 'Diário' },
      { texto: 'Identificar profissionais que necessitam de suporte.', freq: 'Diário' },
      { texto: 'Identificar profissionais destaque.', freq: 'Diário' },
      { texto: 'Identificar profissionais em risco.', freq: 'Diário' },
      { texto: 'Dar feedback positivo quando aplicável.', freq: 'Diário' },
      { texto: 'Dar feedback corretivo quando necessário.', freq: 'Diário' },
      { texto: 'Registrar ocorrências relevantes.', freq: 'Diário' },
    ],
  },
  {
    nome: 'RECEPÇÃO',
    itens: [
      { texto: 'Comunicação e postura — Verificar linguagem utilizada pela recepção.', freq: 'Diário' },
      { texto: 'Comunicação e postura — Verificar cordialidade.', freq: 'Diário' },
      { texto: 'Comunicação e postura — Verificar postura corporal.', freq: 'Diário' },
      { texto: 'Comunicação e postura — Verificar desenvoltura.', freq: 'Diário' },
      { texto: 'Comunicação e postura — Verificar atenção.', freq: 'Diário' },
      { texto: 'Comunicação e postura — Verificar velocidade de resposta.', freq: 'Diário' },
      { texto: 'Comunicação e postura — Verificar comunicação com clientes.', freq: 'Diário' },
      { texto: 'Comunicação e postura — Verificar comunicação com profissionais.', freq: 'Diário' },
      { texto: 'Comunicação e postura — Verificar envio das mensagens padrão.', freq: 'Diário' },
      { texto: 'Comunicação e postura — Corrigir falhas de comunicação.', freq: 'Diário' },
      { texto: 'Agendamento — Conferir erros de agendamento.', freq: 'Diário' },
      { texto: 'Agendamento — Conferir clientes agendadas com profissional errado.', freq: 'Diário' },
      { texto: 'Agendamento — Conferir clientes sem agendamento.', freq: 'Diário' },
      { texto: 'Agendamento — Conferir horários.', freq: 'Diário' },
      { texto: 'Agendamento — Conferir serviços.', freq: 'Diário' },
      { texto: 'Agendamento — Conferir agendamentos múltiplos.', freq: 'Diário' },
      { texto: 'Agendamento — Conferir grandes grupos.', freq: 'Diário' },
      { texto: 'Agendamento — Orientar recepção sobre ajustes necessários.', freq: 'Diário' },
      { texto: 'Desenvolvimento — Treinar caixas.', freq: 'Diário' },
      { texto: 'Desenvolvimento — Treinar recepção.', freq: 'Diário' },
      { texto: 'Desenvolvimento — Realizar feedbacks.', freq: 'Diário' },
      { texto: 'Desenvolvimento — Corrigir comportamentos.', freq: 'Diário' },
      { texto: 'Desenvolvimento — Acompanhar evolução.', freq: 'Diário' },
      { texto: 'Desenvolvimento — Identificar necessidades de treinamento.', freq: 'Diário' },
    ],
  },
  {
    nome: 'EXPERIÊNCIA DO CLIENTE',
    itens: [
      { texto: 'Acompanhar chegada dos clientes.', freq: 'Diário' },
      { texto: 'Garantir acolhimento.', freq: 'Diário' },
      { texto: 'Acompanhar tempo de espera.', freq: 'Diário' },
      { texto: 'Acompanhar atrasos.', freq: 'Diário' },
      { texto: 'Resolver problemas de atendimento.', freq: 'Diário' },
      { texto: 'Acompanhar satisfação.', freq: 'Diário' },
      { texto: 'Garantir qualidade do atendimento.', freq: 'Diário' },
      { texto: 'Garantir padrão de comunicação.', freq: 'Diário' },
      { texto: 'Acompanhar clientes especiais.', freq: 'Diário' },
      { texto: 'Acompanhar noivas.', freq: 'Diário' },
      { texto: 'Acompanhar grandes grupos.', freq: 'Diário' },
      { texto: 'Elaborar orçamentos quando necessário.', freq: 'Diário' },
      { texto: 'Manter relacionamento com clientes especiais.', freq: 'Diário' },
      { texto: 'Resolver reclamações.', freq: 'Diário' },
      { texto: 'Realizar pós-venda quando aplicável.', freq: 'Diário' },
      { texto: 'Garantir encantamento.', freq: 'Diário' },
      { texto: 'Preservar a experiência do cliente.', freq: 'Diário' },
    ],
  },
  {
    nome: 'CLIENTE NÃO GOSTOU DO PROCEDIMENTO',
    itens: [
      { texto: 'Ouvir o cliente.', freq: 'Mensal' },
      { texto: 'Entender exatamente o motivo da insatisfação.', freq: 'Mensal' },
      { texto: 'Ouvir o profissional.', freq: 'Mensal' },
      { texto: 'Confirmar os fatos.', freq: 'Mensal' },
      { texto: 'Avaliar o procedimento realizado.', freq: 'Mensal' },
      { texto: 'Consultar o POP correspondente.', freq: 'Mensal' },
      { texto: 'Identificar se houve falha técnica.', freq: 'Mensal' },
      { texto: 'Identificar se houve falha de comunicação.', freq: 'Mensal' },
      { texto: 'Identificar se houve falha de expectativa.', freq: 'Mensal' },
      { texto: 'Definir ação corretiva.', freq: 'Mensal' },
      { texto: 'Alinhar com o profissional.', freq: 'Mensal' },
      { texto: 'Preservar o relacionamento com o cliente.', freq: 'Mensal' },
      { texto: 'Registrar a ocorrência quando aplicável.', freq: 'Mensal' },
      { texto: 'Acompanhar a solução.', freq: 'Mensal' },
      { texto: 'Encerrar a ocorrência somente após a solução.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'INSATISFAÇÃO NO ATENDIMENTO',
    itens: [
      { texto: 'Profissional — Identificar a origem da insatisfação.', freq: 'Mensal' },
      { texto: 'Profissional — Ouvir o profissional.', freq: 'Mensal' },
      { texto: 'Profissional — Verificar fatos.', freq: 'Mensal' },
      { texto: 'Profissional — Avaliar postura.', freq: 'Mensal' },
      { texto: 'Profissional — Avaliar comunicação.', freq: 'Mensal' },
      { texto: 'Profissional — Avaliar qualidade técnica.', freq: 'Mensal' },
      { texto: 'Profissional — Realizar feedback.', freq: 'Mensal' },
      { texto: 'Profissional — Definir ação corretiva.', freq: 'Mensal' },
      { texto: 'Profissional — Acompanhar evolução.', freq: 'Mensal' },
      { texto: 'Cliente — Ouvir o cliente.', freq: 'Mensal' },
      { texto: 'Cliente — Identificar reclamação.', freq: 'Mensal' },
      { texto: 'Cliente — Resolver problema.', freq: 'Mensal' },
      { texto: 'Cliente — Preservar experiência.', freq: 'Mensal' },
      { texto: 'Cliente — Dar retorno ao cliente.', freq: 'Mensal' },
      { texto: 'Cliente — Alinhar com profissional.', freq: 'Mensal' },
      { texto: 'Cliente — Registrar feedback negativo.', freq: 'Mensal' },
      { texto: 'Cliente — Acompanhar reincidências.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CLIENTE NÃO QUER PAGAR O VALOR LANÇADO NO SISTEMA',
    itens: [
      { texto: 'Ouvir o cliente.', freq: 'Mensal' },
      { texto: 'Verificar valor lançado.', freq: 'Mensal' },
      { texto: 'Conferir serviço realizado.', freq: 'Mensal' },
      { texto: 'Conferir tabela/preço aplicável.', freq: 'Mensal' },
      { texto: 'Conferir se houve erro de lançamento.', freq: 'Mensal' },
      { texto: 'Conferir se houve erro de comunicação do valor.', freq: 'Mensal' },
      { texto: 'Conferir se houve serviço adicional.', freq: 'Mensal' },
      { texto: 'Não alterar valor sem autorização quando a situação exigir decisão da Gerência.', freq: 'Mensal' },
      { texto: 'Acionar Gerência quando necessário.', freq: 'Mensal' },
      { texto: 'Resolver a divergência.', freq: 'Mensal' },
      { texto: 'Registrar ocorrência quando aplicável.', freq: 'Mensal' },
      { texto: 'Corrigir o lançamento caso tenha ocorrido erro.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'SISTEMA E LANÇAMENTO DE SERVIÇOS',
    itens: [
      { texto: 'Conferir se todos os serviços foram lançados.', freq: 'Diário' },
      { texto: 'Conferir se o serviço lançado corresponde ao realizado.', freq: 'Diário' },
      { texto: 'Identificar procedimento não lançado.', freq: 'Diário' },
      { texto: 'Identificar procedimento lançado incorretamente.', freq: 'Diário' },
      { texto: 'Corrigir lançamentos autorizados.', freq: 'Diário' },
      { texto: 'Conferir valores.', freq: 'Diário' },
      { texto: 'Conferir serviços internos.', freq: 'Diário' },
      { texto: 'Conferir lançamentos financeiros.', freq: 'Diário' },
      { texto: 'Identificar erros de sistema.', freq: 'Diário' },
      { texto: 'Registrar divergências.', freq: 'Diário' },
      { texto: 'Encaminhar problemas que não possam ser solucionados pela Coordenação.', freq: 'Diário' },
    ],
  },
  {
    nome: 'SERVIÇOS INTERNOS',
    itens: [
      { texto: 'Conferir serviços internos agendados.', freq: 'Diário' },
      { texto: 'Conferir profissional responsável.', freq: 'Diário' },
      { texto: 'Verificar se os serviços estão sendo realizados.', freq: 'Diário' },
      { texto: 'Verificar se houve atraso.', freq: 'Diário' },
      { texto: 'Verificar se houve cancelamento.', freq: 'Diário' },
      { texto: 'Verificar se houve falta.', freq: 'Diário' },
      { texto: 'Verificar se o serviço interno foi lançado corretamente.', freq: 'Diário' },
      { texto: 'Verificar necessidade de reagendamento.', freq: 'Diário' },
      { texto: 'Acompanhar a execução.', freq: 'Diário' },
    ],
  },
  {
    nome: 'MATERIAIS DE TRABALHO DOS PROFISSIONAIS',
    itens: [
      { texto: 'Conferir material de uso dos profissionais.', freq: 'Semanal' },
      { texto: 'Verificar validade.', freq: 'Semanal' },
      { texto: 'Verificar qualidade dos produtos.', freq: 'Semanal' },
      { texto: 'Verificar conservação.', freq: 'Semanal' },
      { texto: 'Verificar quantidade.', freq: 'Semanal' },
      { texto: 'Verificar necessidade de reposição.', freq: 'Semanal' },
      { texto: 'Conferir materiais das manicures.', freq: 'Semanal' },
      { texto: 'Verificar kits das manicures.', freq: 'Semanal' },
      { texto: 'Verificar se as solicitações foram realizadas nas duas quinzenas.', freq: 'Semanal' },
      { texto: 'Verificar materiais da dosagem.', freq: 'Semanal' },
      { texto: 'Verificar materiais complementares.', freq: 'Semanal' },
      { texto: 'Registrar necessidades de compra.', freq: 'Semanal' },
      { texto: 'Solicitar compras quando necessário.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'CONTROLE DE MATERIAIS ESPECÍFICOS',
    itens: [
      { texto: 'Lista de café.', freq: 'Semanal' },
      { texto: 'Lista de serviços internos para a dosagem.', freq: 'Semanal' },
      { texto: 'Lista de alicates para a dosagem.', freq: 'Semanal' },
      { texto: 'Lista de complemento para a dosagem.', freq: 'Semanal' },
      { texto: 'Lista de corte.', freq: 'Semanal' },
      { texto: 'Lista de pigmentação.', freq: 'Semanal' },
      { texto: 'Lista de mechas.', freq: 'Semanal' },
      { texto: 'Lista de realinhamento.', freq: 'Semanal' },
      { texto: 'Conferir necessidades específicas de cada área.', freq: 'Semanal' },
      { texto: 'Encaminhar necessidades para compra/reposição.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'ESTERILIZAÇÃO E ALICATES',
    itens: [
      { texto: 'Conferir lista de alicates.', freq: 'Semanal' },
      { texto: 'Verificar se todas as manicures estão esterilizando os alicates.', freq: 'Semanal' },
      { texto: 'Conferir assinatura do controle de esterilização.', freq: 'Semanal' },
      { texto: 'Identificar quem não assinou.', freq: 'Semanal' },
      { texto: 'Realizar orientação imediata.', freq: 'Semanal' },
      { texto: 'Registrar reincidências.', freq: 'Semanal' },
      { texto: 'Acompanhar cumprimento do procedimento.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'DOSAGEM',
    itens: [
      { texto: 'Verificar com a Dosadora o que precisa comprar.', freq: 'Semanal' },
      { texto: 'Verificar o que precisa ser ajustado.', freq: 'Semanal' },
      { texto: 'Solicitar organização dos materiais da dosagem nos dois estoques.', freq: 'Semanal' },
      { texto: 'Conferir materiais.', freq: 'Semanal' },
      { texto: 'Conferir validade.', freq: 'Semanal' },
      { texto: 'Conferir qualidade dos produtos.', freq: 'Semanal' },
      { texto: 'Conferir organização.', freq: 'Semanal' },
      { texto: 'Conferir necessidade de reposição.', freq: 'Semanal' },
      { texto: 'Acompanhar correções.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'ESTOQUES',
    itens: [
      { texto: 'Estoque da dosagem — Solicitar organização.', freq: 'Semanal' },
      { texto: 'Estoque da dosagem — Conferir organização.', freq: 'Semanal' },
      { texto: 'Estoque da dosagem — Conferir materiais.', freq: 'Semanal' },
      { texto: 'Estoque da dosagem — Conferir validade.', freq: 'Semanal' },
      { texto: 'Estoque da dosagem — Conferir necessidade de reposição.', freq: 'Semanal' },
      { texto: 'Estoque de higienização — Solicitar organização à auxiliar de serviços gerais.', freq: 'Semanal' },
      { texto: 'Estoque de higienização — Conferir materiais.', freq: 'Semanal' },
      { texto: 'Estoque de higienização — Conferir organização.', freq: 'Semanal' },
      { texto: 'Estoque de higienização — Conferir necessidade de reposição.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'LIMPEZA E ORGANIZAÇÃO',
    itens: [
      { texto: 'Responsabilidade da equipe — Conferir se os profissionais mantêm suas áreas organizadas.', freq: 'Semanal' },
      { texto: 'Responsabilidade da equipe — Conferir materiais fora do lugar.', freq: 'Semanal' },
      { texto: 'Responsabilidade da equipe — Conferir estações de trabalho.', freq: 'Semanal' },
      { texto: 'Responsabilidade da equipe — Orientar profissionais quando necessário.', freq: 'Semanal' },
      { texto: 'Auxiliar de limpeza — Fiscalizar limpeza geral.', freq: 'Semanal' },
      { texto: 'Auxiliar de limpeza — Solicitar limpeza de rodapés.', freq: 'Semanal' },
      { texto: 'Auxiliar de limpeza — Solicitar limpeza das paredes.', freq: 'Semanal' },
      { texto: 'Auxiliar de limpeza — Solicitar limpeza dos rodapés das cadeiras.', freq: 'Semanal' },
      { texto: 'Auxiliar de limpeza — Solicitar limpeza dos apoios de pé.', freq: 'Semanal' },
      { texto: 'Auxiliar de limpeza — Solicitar faxina geral.', freq: 'Semanal' },
      { texto: 'Auxiliar de limpeza — Solicitar limpeza da copa.', freq: 'Semanal' },
      { texto: 'Auxiliar de limpeza — Solicitar limpeza dos estofados.', freq: 'Semanal' },
      { texto: 'Auxiliar de limpeza — Solicitar limpeza das bancadas.', freq: 'Semanal' },
      { texto: 'Auxiliar de limpeza — Solicitar limpeza do teto.', freq: 'Semanal' },
      { texto: 'Auxiliar de limpeza — Conferir execução.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'CONFERÊNCIA DA LIMPEZA — 15H30',
    itens: [
      { texto: 'Verificar dispositivos de papel higiênico.', freq: 'Diário' },
      { texto: 'Verificar papel-toalha.', freq: 'Diário' },
      { texto: 'Limpar/trocar todos os lixos.', freq: 'Diário' },
      { texto: 'Lavar pias e cantos do banheiro.', freq: 'Diário' },
      { texto: 'Lavar vaso sanitário.', freq: 'Diário' },
      { texto: 'Limpar espelho do banheiro.', freq: 'Diário' },
      { texto: 'Lavar chão do banheiro.', freq: 'Diário' },
      { texto: 'Repor sabonete.', freq: 'Diário' },
      { texto: 'Aplicar aromatizador/cheirinho.', freq: 'Diário' },
      { texto: 'Verificar abastecimento de papel higiênico.', freq: 'Diário' },
      { texto: 'Verificar abastecimento de papel-toalha.', freq: 'Diário' },
      { texto: 'Limpar o centro do salão com pano.', freq: 'Diário' },
      { texto: 'Conferir EPIs.', freq: 'Diário' },
      { texto: 'Conferir esterilização/assinaturas das manicures.', freq: 'Diário' },
    ],
  },
  {
    nome: 'CAFÉ E HOSPITALIDADE',
    itens: [
      { texto: 'Conferir café.', freq: 'Diário' },
      { texto: 'Conferir máquina de café.', freq: 'Diário' },
      { texto: 'Conferir limpeza da máquina.', freq: 'Diário' },
      { texto: 'Conferir copos.', freq: 'Diário' },
      { texto: 'Conferir água.', freq: 'Diário' },
      { texto: 'Conferir açúcar sachê.', freq: 'Diário' },
      { texto: 'Conferir adoçante sachê.', freq: 'Diário' },
      { texto: 'Conferir bicarbonato.', freq: 'Diário' },
      { texto: 'Conferir biscoito de queijo.', freq: 'Diário' },
      { texto: 'Conferir café em grão.', freq: 'Diário' },
      { texto: 'Conferir canela em pó.', freq: 'Diário' },
      { texto: 'Conferir chantilly em pó.', freq: 'Diário' },
      { texto: 'Conferir chás.', freq: 'Diário' },
      { texto: 'Conferir chá gelado.', freq: 'Diário' },
      { texto: 'Conferir chocolate em pó.', freq: 'Diário' },
      { texto: 'Conferir Coca Zero.', freq: 'Diário' },
      { texto: 'Conferir Coca-Cola.', freq: 'Diário' },
      { texto: 'Conferir copos descartáveis de água.', freq: 'Diário' },
      { texto: 'Conferir gelo.', freq: 'Diário' },
      { texto: 'Conferir guardanapos.', freq: 'Diário' },
      { texto: 'Conferir leite em pó.', freq: 'Diário' },
      { texto: 'Conferir limão.', freq: 'Diário' },
      { texto: 'Conferir mexedores de café.', freq: 'Diário' },
      { texto: 'Conferir Nescafé.', freq: 'Diário' },
      { texto: 'Conferir pratos descartáveis.', freq: 'Diário' },
      { texto: 'Conferir sucos.', freq: 'Diário' },
      { texto: 'Conferir organização da copa.', freq: 'Diário' },
      { texto: 'Organizar coffee break quando necessário.', freq: 'Diário' },
    ],
  },
  {
    nome: 'BOLOS E ANIVERSARIANTES DO MÊS',
    itens: [
      { texto: 'Verificar qual é a data atual.', freq: 'Mensal' },
      { texto: 'Verificar lista de aniversariantes do mês.', freq: 'Mensal' },
      { texto: 'Enviar mensagem de feliz aniversário para os clientes do mês.', freq: 'Mensal' },
      { texto: 'Verificar com o Gerente o dia do aniversariante do mês.', freq: 'Mensal' },
      { texto: 'Confirmar a data do evento interno.', freq: 'Mensal' },
      { texto: 'Fechar/bloquear a agenda no dia do aniversariante do mês em 30 minutos, conforme planejamento.', freq: 'Mensal' },
      { texto: 'Solicitar à Bruna o bolo.', freq: 'Mensal' },
      { texto: 'Passar para a Bruna a lista de pessoas que irão fazer aniversário.', freq: 'Mensal' },
      { texto: 'Lembrar a Bruna sobre o bolo.', freq: 'Mensal' },
      { texto: 'Conferir vela de aniversário.', freq: 'Mensal' },
      { texto: 'Conferir bolo da Ivone em fatia.', freq: 'Mensal' },
      { texto: 'Conferir bolo no pote.', freq: 'Mensal' },
      { texto: 'Conferir colher para bolo em fatia.', freq: 'Mensal' },
      { texto: 'Conferir embalagens para bolo em fatia.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'MATERIAIS ADMINISTRATIVOS',
    itens: [
      { texto: 'Lápis.', freq: 'Mensal' },
      { texto: 'Canetas.', freq: 'Mensal' },
      { texto: 'Apontador.', freq: 'Mensal' },
      { texto: 'Clips.', freq: 'Mensal' },
      { texto: 'Etiquetas de preço.', freq: 'Mensal' },
      { texto: 'Etiquetas de preço adicionais, quando necessário.', freq: 'Mensal' },
      { texto: 'Bobinas das máquinas.', freq: 'Mensal' },
      { texto: 'Potes de shampoo.', freq: 'Mensal' },
      { texto: 'Sacolas para chinelos de clientes.', freq: 'Mensal' },
      { texto: 'Pratos descartáveis.', freq: 'Mensal' },
      { texto: 'Copos.', freq: 'Mensal' },
      { texto: 'Guardanapos.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'BEBIDAS E EVENTOS',
    itens: [
      { texto: 'Vinho branco.', freq: 'Mensal' },
      { texto: 'Vinho tinto.', freq: 'Mensal' },
      { texto: 'Cerveja Stella Artois.', freq: 'Mensal' },
      { texto: 'Coca-Cola.', freq: 'Mensal' },
      { texto: 'Coca Zero.', freq: 'Mensal' },
      { texto: 'Sucos.', freq: 'Mensal' },
      { texto: 'Chá gelado.', freq: 'Mensal' },
      { texto: 'Gelo.', freq: 'Mensal' },
      { texto: 'Conferir quantidade para eventos.', freq: 'Mensal' },
      { texto: 'Solicitar reposição quando necessário.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'MANUTENÇÃO DA ESTRUTURA',
    itens: [
      { texto: 'Hidráulicos das cadeiras funcionando.', freq: 'Semanal' },
      { texto: 'Tomadas funcionando.', freq: 'Semanal' },
      { texto: 'Lavatórios sem vazamentos.', freq: 'Semanal' },
      { texto: 'Temperatura dos lavatórios adequada.', freq: 'Semanal' },
      { texto: 'Lavatórios em perfeito funcionamento.', freq: 'Semanal' },
      { texto: 'Lâmpadas funcionando.', freq: 'Semanal' },
      { texto: 'Identificar lâmpadas queimadas.', freq: 'Semanal' },
      { texto: 'Verificar pinturas do salão.', freq: 'Semanal' },
      { texto: 'Verificar estofados.', freq: 'Semanal' },
      { texto: 'Verificar gavetas das manicures.', freq: 'Semanal' },
      { texto: 'Verificar gavetas da dosagem.', freq: 'Semanal' },
      { texto: 'Verificar armários.', freq: 'Semanal' },
      { texto: 'Verificar jardim.', freq: 'Semanal' },
      { texto: 'Verificar ar-condicionado.', freq: 'Semanal' },
      { texto: 'Verificar vidros principais.', freq: 'Semanal' },
      { texto: 'Conferir limpeza dos vidros principais.', freq: 'Semanal' },
      { texto: 'Verificar carrinhos.', freq: 'Semanal' },
      { texto: 'Verificar rodas dos carrinhos.', freq: 'Semanal' },
      { texto: 'Solicitar manutenção quando necessário.', freq: 'Semanal' },
      { texto: 'Registrar problemas.', freq: 'Semanal' },
      { texto: 'Acompanhar solução.', freq: 'Semanal' },
      { texto: 'Confirmar conclusão da manutenção.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'AÇÕES COMERCIAIS',
    itens: [
      { texto: 'Verificar ações comerciais vigentes.', freq: 'Semanal' },
      { texto: 'Relembrar profissionais sobre as ações.', freq: 'Semanal' },
      { texto: 'Orientar equipe sobre ações comerciais internas.', freq: 'Semanal' },
      { texto: 'Orientar equipe sobre ações comerciais externas.', freq: 'Semanal' },
      { texto: 'Conferir se os profissionais conhecem as campanhas.', freq: 'Semanal' },
      { texto: 'Estimular divulgação das ações.', freq: 'Semanal' },
      { texto: 'Acompanhar execução.', freq: 'Semanal' },
      { texto: 'Identificar oportunidades comerciais.', freq: 'Semanal' },
      { texto: 'Recolher ideias de ações dos profissionais.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'FOTOS E MARKETING',
    itens: [
      { texto: 'Solicitar que todos os profissionais tirem fotos dos serviços realizados diariamente.', freq: 'Semanal' },
      { texto: 'Solicitar envio das fotos para o Drive.', freq: 'Semanal' },
      { texto: 'Conferir se as fotos estão sendo enviadas.', freq: 'Semanal' },
      { texto: 'Garantir que o material esteja disponível para o Marketing.', freq: 'Semanal' },
      { texto: 'Reforçar diariamente quando necessário.', freq: 'Semanal' },
      { texto: 'Verificar calendário da planilha central.', freq: 'Semanal' },
      { texto: 'Identificar datas de eventos.', freq: 'Semanal' },
      { texto: 'Repassar eventos à equipe.', freq: 'Semanal' },
      { texto: 'Enviar lembretes sobre eventos.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'RECOLHIMENTO DE DEMANDAS DOS PROFISSIONAIS',
    itens: [
      { texto: 'Recolher demandas financeiras.', freq: 'Semanal' },
      { texto: 'Recolher solicitações de ajustes.', freq: 'Semanal' },
      { texto: 'Recolher lançamentos incorretos.', freq: 'Semanal' },
      { texto: 'Recolher necessidades de compra de produtos.', freq: 'Semanal' },
      { texto: 'Recolher ideias de ações.', freq: 'Semanal' },
      { texto: 'Recolher problemas operacionais.', freq: 'Semanal' },
      { texto: 'Recolher necessidades de treinamento.', freq: 'Semanal' },
      { texto: 'Resolver demandas de competência da Coordenação.', freq: 'Semanal' },
      { texto: 'Encaminhar demandas à Gerência quando necessário.', freq: 'Semanal' },
      { texto: 'Acompanhar resolução das demandas.', freq: 'Semanal' },
      { texto: 'Dar retorno ao profissional.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'CONFLITOS E RELACIONAMENTOS',
    itens: [
      { texto: 'Profissional x profissional — Ouvir as partes.', freq: 'Mensal' },
      { texto: 'Profissional x profissional — Confirmar fatos.', freq: 'Mensal' },
      { texto: 'Profissional x profissional — Evitar julgamento precipitado.', freq: 'Mensal' },
      { texto: 'Profissional x profissional — Consultar normas/POPs.', freq: 'Mensal' },
      { texto: 'Profissional x profissional — Realizar alinhamento.', freq: 'Mensal' },
      { texto: 'Profissional x profissional — Definir ação corretiva.', freq: 'Mensal' },
      { texto: 'Profissional x profissional — Registrar quando necessário.', freq: 'Mensal' },
      { texto: 'Profissional x profissional — Acompanhar relacionamento.', freq: 'Mensal' },
      { texto: 'Profissional x cliente — Ouvir cliente.', freq: 'Mensal' },
      { texto: 'Profissional x cliente — Ouvir profissional.', freq: 'Mensal' },
      { texto: 'Profissional x cliente — Preservar respeito.', freq: 'Mensal' },
      { texto: 'Profissional x cliente — Resolver situação.', freq: 'Mensal' },
      { texto: 'Profissional x cliente — Proteger experiência do cliente.', freq: 'Mensal' },
      { texto: 'Profissional x cliente — Registrar ocorrência quando necessário.', freq: 'Mensal' },
      { texto: 'Profissional x cliente — Acompanhar solução.', freq: 'Mensal' },
      { texto: 'Profissional x recepção — Ouvir ambas as partes.', freq: 'Mensal' },
      { texto: 'Profissional x recepção — Confirmar fatos.', freq: 'Mensal' },
      { texto: 'Profissional x recepção — Identificar falha de comunicação.', freq: 'Mensal' },
      { texto: 'Profissional x recepção — Realizar alinhamento.', freq: 'Mensal' },
      { texto: 'Profissional x recepção — Definir padrão esperado.', freq: 'Mensal' },
      { texto: 'Profissional x recepção — Acompanhar reincidência.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'SITUAÇÕES OBRIGATÓRIAS DE ALINHAMENTO',
    itens: [
      { texto: 'Limpeza inadequada.', freq: 'Mensal' },
      { texto: 'Falta de organização.', freq: 'Mensal' },
      { texto: 'Material fora do lugar.', freq: 'Mensal' },
      { texto: 'Equipamento sem conservação.', freq: 'Mensal' },
      { texto: 'Falta de conferência de materiais.', freq: 'Mensal' },
      { texto: 'Uso inadequado de EPI.', freq: 'Mensal' },
      { texto: 'Uniforme fora do padrão.', freq: 'Mensal' },
      { texto: 'Cliente insatisfeito.', freq: 'Mensal' },
      { texto: 'Cliente não gostou do procedimento.', freq: 'Mensal' },
      { texto: 'Atendimento inadequado.', freq: 'Mensal' },
      { texto: 'Falta de acolhimento.', freq: 'Mensal' },
      { texto: 'Falta de comunicação.', freq: 'Mensal' },
      { texto: 'Reclamação.', freq: 'Mensal' },
      { texto: 'Feedback negativo.', freq: 'Mensal' },
      { texto: 'Procedimento fora do padrão.', freq: 'Mensal' },
      { texto: 'Procedimento lançado incorretamente.', freq: 'Mensal' },
      { texto: 'Procedimento não lançado.', freq: 'Mensal' },
      { texto: 'Atendimento pelo profissional errado.', freq: 'Mensal' },
      { texto: 'Cliente agendada com profissional incorreto.', freq: 'Mensal' },
      { texto: 'Cliente sem agendamento.', freq: 'Mensal' },
      { texto: 'Profissional negar cliente.', freq: 'Mensal' },
      { texto: 'Profissional ir embora deixando cliente na agenda.', freq: 'Mensal' },
      { texto: 'Atraso de profissional.', freq: 'Mensal' },
      { texto: 'Falta de profissional.', freq: 'Mensal' },
      { texto: 'Erro de agenda.', freq: 'Mensal' },
      { texto: 'Erro de sistema.', freq: 'Mensal' },
      { texto: 'Serviço interno não realizado.', freq: 'Mensal' },
      { texto: 'Lançamento incorreto.', freq: 'Mensal' },
      { texto: 'Não lançamento de procedimento.', freq: 'Mensal' },
      { texto: 'Cliente questionando valor.', freq: 'Mensal' },
      { texto: 'Cliente recusando pagamento.', freq: 'Mensal' },
      { texto: 'Divergência de cobrança.', freq: 'Mensal' },
      { texto: 'Erro financeiro.', freq: 'Mensal' },
      { texto: 'Conflito entre profissionais.', freq: 'Mensal' },
      { texto: 'Conflito recepção x profissional.', freq: 'Mensal' },
      { texto: 'Conflito cliente x profissional.', freq: 'Mensal' },
      { texto: 'Comunicação inadequada.', freq: 'Mensal' },
      { texto: 'Desrespeito.', freq: 'Mensal' },
      { texto: 'Falta de colaboração.', freq: 'Mensal' },
      { texto: 'Erro de agendamento da recepção.', freq: 'Mensal' },
      { texto: 'Postura inadequada da recepção.', freq: 'Mensal' },
      { texto: 'Falta de cordialidade.', freq: 'Mensal' },
      { texto: 'Falta de atenção.', freq: 'Mensal' },
      { texto: 'Lentidão.', freq: 'Mensal' },
      { texto: 'Falta de desenvoltura.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'PADRÃO DE FEEDBACK',
    itens: [
      { texto: 'Sempre que realizar um feedback — Descrever objetivamente o fato.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Apresentar evidências.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Explicar o impacto para o cliente.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Explicar o impacto para a equipe.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Explicar o impacto para a operação.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Explicar o impacto para a empresa.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Reforçar o padrão esperado.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Consultar o POP correspondente.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Ouvir o colaborador.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Permitir esclarecimentos.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Definir ação corretiva.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Definir prazo, quando necessário.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Registrar quando aplicável.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Acompanhar evolução.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Validar melhoria.', freq: 'Mensal' },
      { texto: 'Sempre que realizar um feedback — Encerrar ocorrência.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ESCALA DE CORREÇÃO',
    itens: [
      { texto: 'Primeira ocorrência — Realizar orientação verbal.', freq: 'Mensal' },
      { texto: 'Primeira ocorrência — Registrar internamente quando aplicável.', freq: 'Mensal' },
      { texto: 'Reincidência — Realizar feedback formal.', freq: 'Mensal' },
      { texto: 'Reincidência — Criar plano de melhoria.', freq: 'Mensal' },
      { texto: 'Reincidência — Definir treinamento obrigatório.', freq: 'Mensal' },
      { texto: 'Reincidência — Acompanhar evolução.', freq: 'Mensal' },
      { texto: 'Persistência — Comunicar Gerência.', freq: 'Mensal' },
      { texto: 'Persistência — Apresentar histórico das ocorrências.', freq: 'Mensal' },
      { texto: 'Persistência — Encaminhar para aplicação das medidas administrativas previstas pela empresa.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CONDUTA DO COORDENADOR DURANTE FEEDBACK',
    itens: [
      { texto: 'Manter postura profissional.', freq: 'Mensal' },
      { texto: 'Agir com imparcialidade.', freq: 'Mensal' },
      { texto: 'Não elevar o tom de voz.', freq: 'Mensal' },
      { texto: 'Corrigir comportamento, nunca atacar a pessoa.', freq: 'Mensal' },
      { texto: 'Basear decisões em fatos.', freq: 'Mensal' },
      { texto: 'Utilizar POPs como referência.', freq: 'Mensal' },
      { texto: 'Manter sigilo quando necessário.', freq: 'Mensal' },
      { texto: 'Registrar ocorrências relevantes.', freq: 'Mensal' },
      { texto: 'Acompanhar eficácia das ações corretivas.', freq: 'Mensal' },
      { texto: 'Garantir que o aprendizado seja incorporado à rotina.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'SEGURANÇA E EPI',
    itens: [
      { texto: 'Conferir máscaras.', freq: 'Diário' },
      { texto: 'Conferir luvas.', freq: 'Diário' },
      { texto: 'Conferir jalecos.', freq: 'Diário' },
      { texto: 'Conferir sapatos fechados das manicures.', freq: 'Diário' },
      { texto: 'Verificar utilização correta.', freq: 'Diário' },
      { texto: 'Corrigir desvios.', freq: 'Diário' },
      { texto: 'Registrar reincidências.', freq: 'Diário' },
      { texto: 'Solicitar reposição quando necessário.', freq: 'Diário' },
      { texto: 'Verificar riscos sanitários.', freq: 'Diário' },
      { texto: 'Verificar riscos operacionais.', freq: 'Diário' },
      { texto: 'Verificar riscos de segurança do cliente.', freq: 'Diário' },
      { texto: 'Verificar riscos de segurança da equipe.', freq: 'Diário' },
    ],
  },
  {
    nome: 'GESTÃO DA IMAGEM DO SALÃO',
    itens: [
      { texto: 'Limpeza impecável.', freq: 'Diário' },
      { texto: 'Organização.', freq: 'Diário' },
      { texto: 'Música ambiente.', freq: 'Diário' },
      { texto: 'Aroma.', freq: 'Diário' },
      { texto: 'Iluminação.', freq: 'Diário' },
      { texto: 'Temperatura.', freq: 'Diário' },
      { texto: 'Apresentação da equipe.', freq: 'Diário' },
      { texto: 'Apresentação pessoal.', freq: 'Diário' },
      { texto: 'Postura dos profissionais.', freq: 'Diário' },
      { texto: 'Preservação da imagem da empresa.', freq: 'Diário' },
      { texto: 'Preservação da marca.', freq: 'Diário' },
      { texto: 'Preservação da reputação.', freq: 'Diário' },
    ],
  },
  {
    nome: 'GESTÃO DA EQUIPE',
    itens: [
      { texto: 'Recolher demandas.', freq: 'Semanal' },
      { texto: 'Resolver demandas operacionais.', freq: 'Semanal' },
      { texto: 'Repassar necessidades à Gerência.', freq: 'Semanal' },
      { texto: 'Garantir satisfação da equipe.', freq: 'Semanal' },
      { texto: 'Organizar férias.', freq: 'Semanal' },
      { texto: 'Organizar folgas.', freq: 'Semanal' },
      { texto: 'Organizar escalas.', freq: 'Semanal' },
      { texto: 'Cobrir ausências.', freq: 'Semanal' },
      { texto: 'Garantir equipe suficiente.', freq: 'Semanal' },
      { texto: 'Comunicar ações internas.', freq: 'Semanal' },
      { texto: 'Comunicar ajustes.', freq: 'Semanal' },
      { texto: 'Enviar lembretes.', freq: 'Semanal' },
      { texto: 'Alinhar informações.', freq: 'Semanal' },
      { texto: 'Treinar caixas.', freq: 'Semanal' },
      { texto: 'Treinar recepção.', freq: 'Semanal' },
      { texto: 'Desenvolver colaboradores.', freq: 'Semanal' },
      { texto: 'Realizar feedbacks positivos.', freq: 'Semanal' },
      { texto: 'Corrigir comportamentos.', freq: 'Semanal' },
      { texto: 'Gerir conflitos.', freq: 'Semanal' },
      { texto: 'Acompanhar satisfação da equipe.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'DESENVOLVIMENTO DOS PROFISSIONAIS',
    itens: [
      { texto: 'Mensalmente — Identificar profissionais destaque.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar profissionais em risco.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar necessidades de treinamento.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar potencial de crescimento.', freq: 'Mensal' },
      { texto: 'Mensalmente — Elaborar plano de desenvolvimento.', freq: 'Mensal' },
      { texto: 'Mensalmente — Acompanhar plano.', freq: 'Mensal' },
      { texto: 'Mensalmente — Avaliar evolução.', freq: 'Mensal' },
      { texto: 'Mensalmente — Reconhecer bons resultados.', freq: 'Mensal' },
      { texto: 'Mensalmente — Realizar feedback individual.', freq: 'Mensal' },
      { texto: 'Feedbacks devem contemplar — Comportamento.', freq: 'Mensal' },
      { texto: 'Feedbacks devem contemplar — Atendimento.', freq: 'Mensal' },
      { texto: 'Feedbacks devem contemplar — Organização.', freq: 'Mensal' },
      { texto: 'Feedbacks devem contemplar — Comunicação.', freq: 'Mensal' },
      { texto: 'Feedbacks devem contemplar — Postura.', freq: 'Mensal' },
      { texto: 'Feedbacks devem contemplar — Pontualidade.', freq: 'Mensal' },
      { texto: 'Feedbacks devem contemplar — Produtividade.', freq: 'Mensal' },
      { texto: 'Feedbacks devem contemplar — Qualidade técnica.', freq: 'Mensal' },
      { texto: 'Feedbacks devem contemplar — Trabalho em equipe.', freq: 'Mensal' },
      { texto: 'Feedbacks devem contemplar — Comprometimento.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CLIMA ORGANIZACIONAL — MENSAL',
    itens: [
      { texto: 'Avaliar integração da equipe.', freq: 'Mensal' },
      { texto: 'Avaliar motivação.', freq: 'Mensal' },
      { texto: 'Avaliar comunicação.', freq: 'Mensal' },
      { texto: 'Identificar conflitos.', freq: 'Mensal' },
      { texto: 'Avaliar cooperação.', freq: 'Mensal' },
      { texto: 'Avaliar respeito.', freq: 'Mensal' },
      { texto: 'Avaliar aderência à cultura.', freq: 'Mensal' },
      { texto: 'Identificar problemas recorrentes.', freq: 'Mensal' },
      { texto: 'Definir ações de melhoria.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CULTURA ORGANIZACIONAL',
    itens: [
      { texto: 'Verificar se a equipe vive os valores da empresa.', freq: 'Mensal' },
      { texto: 'Reforçar princípios.', freq: 'Mensal' },
      { texto: 'Reforçar processos.', freq: 'Mensal' },
      { texto: 'Reforçar padrões.', freq: 'Mensal' },
      { texto: 'Reforçar comportamento esperado.', freq: 'Mensal' },
      { texto: 'Garantir que resultados sejam entregues respeitando a cultura.', freq: 'Mensal' },
      { texto: 'Corrigir comportamentos incompatíveis com a cultura.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CONTROLE FINANCEIRO OPERACIONAL',
    itens: [
      { texto: 'Evitar desperdícios.', freq: 'Mensal' },
      { texto: 'Controlar consumo.', freq: 'Mensal' },
      { texto: 'Reduzir retrabalho.', freq: 'Mensal' },
      { texto: 'Reduzir cancelamentos.', freq: 'Mensal' },
      { texto: 'Reduzir faltas.', freq: 'Mensal' },
      { texto: 'Aumentar ocupação das agendas.', freq: 'Mensal' },
      { texto: 'Aumentar produtividade.', freq: 'Mensal' },
      { texto: 'Conferir lançamentos.', freq: 'Mensal' },
      { texto: 'Identificar divergências.', freq: 'Mensal' },
      { texto: 'Encaminhar alterações financeiras à Gerência quando necessário.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'INDICADORES',
    itens: [
      { texto: 'Organização operacional.', freq: 'Mensal' },
      { texto: 'Cumprimento das escalas.', freq: 'Mensal' },
      { texto: 'Satisfação da equipe.', freq: 'Mensal' },
      { texto: 'Satisfação dos clientes.', freq: 'Mensal' },
      { texto: 'Reclamações.', freq: 'Mensal' },
      { texto: 'Retrabalho.', freq: 'Mensal' },
      { texto: 'Pontualidade.', freq: 'Mensal' },
      { texto: 'Organização do salão.', freq: 'Mensal' },
      { texto: 'Tempo de resposta.', freq: 'Mensal' },
      { texto: 'Cumprimento dos processos.', freq: 'Mensal' },
      { texto: 'Qualidade dos feedbacks.', freq: 'Mensal' },
      { texto: 'Desenvolvimento da equipe.', freq: 'Mensal' },
      { texto: 'Analisar causas dos resultados.', freq: 'Mensal' },
      { texto: 'Criar plano de ação.', freq: 'Mensal' },
      { texto: 'Acompanhar evolução.', freq: 'Mensal' },
      { texto: 'Validar resultados.', freq: 'Mensal' },
      { texto: 'Preparar relatórios.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'GESTÃO DE INFORMAÇÕES',
    itens: [
      { texto: 'Registrar informações importantes.', freq: 'Mensal' },
      { texto: 'Documentar ocorrências.', freq: 'Mensal' },
      { texto: 'Comunicar informações relevantes.', freq: 'Mensal' },
      { texto: 'Arquivar registros.', freq: 'Mensal' },
      { texto: 'Atualizar controles.', freq: 'Mensal' },
      { texto: 'Atualizar listas.', freq: 'Mensal' },
      { texto: 'Registrar feedbacks.', freq: 'Mensal' },
      { texto: 'Registrar ações corretivas.', freq: 'Mensal' },
      { texto: 'Registrar demandas.', freq: 'Mensal' },
      { texto: 'Registrar problemas de manutenção.', freq: 'Mensal' },
      { texto: 'Registrar problemas recorrentes.', freq: 'Mensal' },
      { texto: 'Regra: nada importante deve depender apenas da memória.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'PLANILHA DE FEEDBACK',
    itens: [
      { texto: 'Registrar tudo o que aconteceu no salão.', freq: 'Mensal' },
      { texto: 'Registrar feedback positivo.', freq: 'Mensal' },
      { texto: 'Registrar feedback negativo.', freq: 'Mensal' },
      { texto: 'Identificar profissional envolvido.', freq: 'Mensal' },
      { texto: 'Registrar data.', freq: 'Mensal' },
      { texto: 'Registrar situação.', freq: 'Mensal' },
      { texto: 'Registrar ação tomada.', freq: 'Mensal' },
      { texto: 'Registrar responsável.', freq: 'Mensal' },
      { texto: 'Registrar prazo.', freq: 'Mensal' },
      { texto: 'Registrar acompanhamento.', freq: 'Mensal' },
      { texto: 'Registrar encerramento.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'GESTÃO DE RISCOS',
    itens: [
      { texto: 'Verificar — Riscos financeiros.', freq: 'Mensal' },
      { texto: 'Verificar — Riscos operacionais.', freq: 'Mensal' },
      { texto: 'Verificar — Riscos jurídicos.', freq: 'Mensal' },
      { texto: 'Verificar — Riscos sanitários.', freq: 'Mensal' },
      { texto: 'Verificar — Riscos de imagem.', freq: 'Mensal' },
      { texto: 'Verificar — Riscos trabalhistas.', freq: 'Mensal' },
      { texto: 'Verificar — Riscos relacionados ao cliente.', freq: 'Mensal' },
      { texto: 'Verificar — Riscos relacionados à equipe.', freq: 'Mensal' },
      { texto: 'Verificar — Riscos relacionados à estrutura.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'GESTÃO DE CRISES',
    itens: [
      { texto: 'Em situações de — Falta de energia.', freq: 'Mensal' },
      { texto: 'Em situações de — Falta de profissional.', freq: 'Mensal' },
      { texto: 'Em situações de — Atraso generalizado.', freq: 'Mensal' },
      { texto: 'Em situações de — Reclamação grave.', freq: 'Mensal' },
      { texto: 'Em situações de — Acidente.', freq: 'Mensal' },
      { texto: 'Em situações de — Problema técnico.', freq: 'Mensal' },
      { texto: 'Em situações de — Sistema fora do ar.', freq: 'Mensal' },
      { texto: 'O Coordenador deverá — Identificar o problema.', freq: 'Mensal' },
      { texto: 'O Coordenador deverá — Priorizar segurança.', freq: 'Mensal' },
      { texto: 'O Coordenador deverá — Priorizar cliente.', freq: 'Mensal' },
      { texto: 'O Coordenador deverá — Organizar a equipe.', freq: 'Mensal' },
      { texto: 'O Coordenador deverá — Aplicar protocolo específico.', freq: 'Mensal' },
      { texto: 'O Coordenador deverá — Comunicar a Gerência quando necessário.', freq: 'Mensal' },
      { texto: 'O Coordenador deverá — Registrar ocorrência.', freq: 'Mensal' },
      { texto: 'O Coordenador deverá — Acompanhar solução.', freq: 'Mensal' },
      { texto: 'O Coordenador deverá — Avaliar necessidade de ação preventiva.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ORDEM DE PRIORIDADES',
    itens: [
      { texto: 'Em qualquer decisão, seguir — 1. Cliente.', freq: 'Mensal' },
      { texto: 'Em qualquer decisão, seguir — 2. Segurança.', freq: 'Mensal' },
      { texto: 'Em qualquer decisão, seguir — 3. Qualidade.', freq: 'Mensal' },
      { texto: 'Em qualquer decisão, seguir — 4. Processos.', freq: 'Mensal' },
      { texto: 'Em qualquer decisão, seguir — 5. Equipe.', freq: 'Mensal' },
      { texto: 'Em qualquer decisão, seguir — 6. Financeiro.', freq: 'Mensal' },
      { texto: 'Em qualquer decisão, seguir — 7. Organização.', freq: 'Mensal' },
      { texto: 'Antes de decidir, avaliar — Segurança do cliente.', freq: 'Mensal' },
      { texto: 'Antes de decidir, avaliar — Segurança da equipe.', freq: 'Mensal' },
      { texto: 'Antes de decidir, avaliar — Impacto financeiro.', freq: 'Mensal' },
      { texto: 'Antes de decidir, avaliar — Impacto operacional.', freq: 'Mensal' },
      { texto: 'Antes de decidir, avaliar — Impacto na experiência do cliente.', freq: 'Mensal' },
      { texto: 'Antes de decidir, avaliar — Impacto na imagem da empresa.', freq: 'Mensal' },
      { texto: 'Antes de decidir, avaliar — Conformidade com os POPs.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'AUTONOMIA DO COORDENADOR',
    itens: [
      { texto: 'Pode decidir — Troca de horários.', freq: 'Mensal' },
      { texto: 'Pode decidir — Ajustes de agenda.', freq: 'Mensal' },
      { texto: 'Pode decidir — Redistribuição de profissionais.', freq: 'Mensal' },
      { texto: 'Pode decidir — Organização do salão.', freq: 'Mensal' },
      { texto: 'Pode decidir — Correções operacionais.', freq: 'Mensal' },
      { texto: 'Pode decidir — Mudanças de escala.', freq: 'Mensal' },
      { texto: 'Pode decidir — Redistribuição de atendimentos.', freq: 'Mensal' },
      { texto: 'Pode decidir — Solicitação de correções imediatas.', freq: 'Mensal' },
      { texto: 'Pode decidir — Interrupção de procedimento operacional incorreto.', freq: 'Mensal' },
      { texto: 'Pode decidir — Solicitação de treinamentos.', freq: 'Mensal' },
      { texto: 'Pode decidir — Comunicação de ocorrências à Gerência.', freq: 'Mensal' },
      { texto: 'Deve consultar a Gerência — Descontos.', freq: 'Mensal' },
      { texto: 'Deve consultar a Gerência — Demissões.', freq: 'Mensal' },
      { texto: 'Deve consultar a Gerência — Advertências.', freq: 'Mensal' },
      { texto: 'Deve consultar a Gerência — Suspensões.', freq: 'Mensal' },
      { texto: 'Deve consultar a Gerência — Mudanças de processos.', freq: 'Mensal' },
      { texto: 'Deve consultar a Gerência — Compras extraordinárias.', freq: 'Mensal' },
      { texto: 'Deve consultar a Gerência — Alterações financeiras.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'RELAÇÃO COM PROCESSOS E POPs',
    itens: [
      { texto: 'Consultar POP correspondente diante de desvios.', freq: 'Mensal' },
      { texto: 'Garantir cumprimento dos processos.', freq: 'Mensal' },
      { texto: 'Fiscalizar padrões.', freq: 'Mensal' },
      { texto: 'Corrigir desvios.', freq: 'Mensal' },
      { texto: 'Implementar ações corretivas definidas.', freq: 'Mensal' },
      { texto: 'Apoiar auditorias.', freq: 'Mensal' },
      { texto: 'Garantir melhoria contínua.', freq: 'Mensal' },
      { texto: 'Encaminhar sugestões de melhoria ao Responsável por Processos.', freq: 'Mensal' },
      { texto: 'Não criar POPs por conta própria.', freq: 'Mensal' },
      { texto: 'Não alterar procedimentos por conta própria.', freq: 'Mensal' },
      { texto: 'Não modificar fluxos operacionais por conta própria.', freq: 'Mensal' },
      { texto: 'Não aprovar mudanças de processos por conta própria.', freq: 'Mensal' },
      { texto: 'Não alterar documentos oficiais.', freq: 'Mensal' },
      { texto: 'Não definir indicadores de processos.', freq: 'Mensal' },
      { texto: 'Não conduzir auditorias técnicas de conformidade.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ROTINA SEMANAL',
    itens: [
      { texto: 'SEGUNDA — Planejamento — Planejar a semana.', freq: 'Semanal' },
      { texto: 'SEGUNDA — Planejamento — Conferir escalas.', freq: 'Semanal' },
      { texto: 'SEGUNDA — Planejamento — Conferir folgas.', freq: 'Semanal' },
      { texto: 'SEGUNDA — Planejamento — Conferir férias.', freq: 'Semanal' },
      { texto: 'SEGUNDA — Planejamento — Conferir equipe disponível.', freq: 'Semanal' },
      { texto: 'SEGUNDA — Planejamento — Conferir agenda.', freq: 'Semanal' },
      { texto: 'SEGUNDA — Planejamento — Conferir demandas.', freq: 'Semanal' },
      { texto: 'SEGUNDA — Planejamento — Conferir ações comerciais.', freq: 'Semanal' },
      { texto: 'SEGUNDA — Planejamento — Conferir eventos.', freq: 'Semanal' },
      { texto: 'SEGUNDA — Planejamento — Definir prioridades da semana.', freq: 'Semanal' },
      { texto: 'TERÇA — Acompanhamento — Acompanhar execução.', freq: 'Semanal' },
      { texto: 'TERÇA — Acompanhamento — Acompanhar equipe.', freq: 'Semanal' },
      { texto: 'TERÇA — Acompanhamento — Acompanhar agendas.', freq: 'Semanal' },
      { texto: 'TERÇA — Acompanhamento — Acompanhar clientes.', freq: 'Semanal' },
      { texto: 'TERÇA — Acompanhamento — Acompanhar processos.', freq: 'Semanal' },
      { texto: 'TERÇA — Acompanhamento — Acompanhar demandas.', freq: 'Semanal' },
      { texto: 'TERÇA — Acompanhamento — Acompanhar problemas.', freq: 'Semanal' },
      { texto: 'QUARTA — Auditoria — Conferir processos.', freq: 'Semanal' },
      { texto: 'QUARTA — Auditoria — Conferir lançamentos.', freq: 'Semanal' },
      { texto: 'QUARTA — Auditoria — Conferir materiais.', freq: 'Semanal' },
      { texto: 'QUARTA — Auditoria — Conferir organização.', freq: 'Semanal' },
      { texto: 'QUARTA — Auditoria — Conferir qualidade.', freq: 'Semanal' },
      { texto: 'QUARTA — Auditoria — Conferir agendas.', freq: 'Semanal' },
      { texto: 'QUARTA — Auditoria — Identificar desvios.', freq: 'Semanal' },
      { texto: 'QUARTA — Auditoria — Registrar correções.', freq: 'Semanal' },
      { texto: 'QUINTA — Treinamentos — Identificar necessidades.', freq: 'Semanal' },
      { texto: 'QUINTA — Treinamentos — Realizar treinamentos.', freq: 'Semanal' },
      { texto: 'QUINTA — Treinamentos — Treinar recepção.', freq: 'Semanal' },
      { texto: 'QUINTA — Treinamentos — Treinar caixas.', freq: 'Semanal' },
      { texto: 'QUINTA — Treinamentos — Orientar profissionais.', freq: 'Semanal' },
      { texto: 'QUINTA — Treinamentos — Acompanhar aprendizado.', freq: 'Semanal' },
      { texto: 'SEXTA — Indicadores — Conferir indicadores.', freq: 'Semanal' },
      { texto: 'SEXTA — Indicadores — Analisar resultados.', freq: 'Semanal' },
      { texto: 'SEXTA — Indicadores — Identificar causas.', freq: 'Semanal' },
      { texto: 'SEXTA — Indicadores — Criar ações.', freq: 'Semanal' },
      { texto: 'SEXTA — Indicadores — Acompanhar evolução.', freq: 'Semanal' },
      { texto: 'SEXTA — Indicadores — Preparar informações para Gerência.', freq: 'Semanal' },
      { texto: 'SÁBADO — Avaliação da operação — Avaliar funcionamento do salão.', freq: 'Semanal' },
      { texto: 'SÁBADO — Avaliação da operação — Avaliar equipe.', freq: 'Semanal' },
      { texto: 'SÁBADO — Avaliação da operação — Avaliar agenda.', freq: 'Semanal' },
      { texto: 'SÁBADO — Avaliação da operação — Avaliar atendimento.', freq: 'Semanal' },
      { texto: 'SÁBADO — Avaliação da operação — Avaliar organização.', freq: 'Semanal' },
      { texto: 'SÁBADO — Avaliação da operação — Avaliar problemas ocorridos.', freq: 'Semanal' },
      { texto: 'SÁBADO — Avaliação da operação — Registrar pendências para a próxima semana.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'DOMINGO — ESCALA E OPERAÇÃO',
    itens: [
      { texto: 'Organizar agendas conforme escala.', freq: 'Semanal' },
      { texto: 'Verificar profissionais suficientes para a demanda.', freq: 'Semanal' },
      { texto: 'Identificar desfalques.', freq: 'Semanal' },
      { texto: 'Ajustar desfalques com outro profissional.', freq: 'Semanal' },
      { texto: 'Conferir agenda.', freq: 'Semanal' },
      { texto: 'Conferir horários.', freq: 'Semanal' },
      { texto: 'Conferir profissionais.', freq: 'Semanal' },
      { texto: 'Antecipar possíveis problemas.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'ROTINA MENSAL',
    itens: [
      { texto: 'Realizar feedback individual.', freq: 'Mensal' },
      { texto: 'Realizar auditoria completa.', freq: 'Mensal' },
      { texto: 'Revisar metas.', freq: 'Mensal' },
      { texto: 'Revisar POPs junto aos responsáveis.', freq: 'Mensal' },
      { texto: 'Elaborar plano de melhoria.', freq: 'Mensal' },
      { texto: 'Realizar reunião com a Gerência.', freq: 'Mensal' },
      { texto: 'Elaborar plano do próximo mês.', freq: 'Mensal' },
      { texto: 'Avaliar clima organizacional.', freq: 'Mensal' },
      { texto: 'Avaliar profissionais destaque.', freq: 'Mensal' },
      { texto: 'Avaliar profissionais em risco.', freq: 'Mensal' },
      { texto: 'Identificar necessidades de treinamento.', freq: 'Mensal' },
      { texto: 'Avaliar indicadores.', freq: 'Mensal' },
      { texto: 'Avaliar reclamações.', freq: 'Mensal' },
      { texto: 'Avaliar retrabalho.', freq: 'Mensal' },
      { texto: 'Avaliar pontualidade.', freq: 'Mensal' },
      { texto: 'Avaliar satisfação dos clientes.', freq: 'Mensal' },
      { texto: 'Avaliar satisfação da equipe.', freq: 'Mensal' },
      { texto: 'Avaliar manutenção.', freq: 'Mensal' },
      { texto: 'Avaliar estoque.', freq: 'Mensal' },
      { texto: 'Avaliar materiais.', freq: 'Mensal' },
      { texto: 'Avaliar ações comerciais.', freq: 'Mensal' },
      { texto: 'Avaliar resultados.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CHECKLIST DE ENCERRAMENTO DO DIA',
    itens: [
      { texto: 'Conferir se todos os clientes foram atendidos.', freq: 'Diário' },
      { texto: 'Conferir clientes ainda na agenda.', freq: 'Diário' },
      { texto: 'Conferir se algum profissional está deixando cliente agendado.', freq: 'Diário' },
      { texto: 'Conferir lançamentos.', freq: 'Diário' },
      { texto: 'Conferir procedimentos não lançados.', freq: 'Diário' },
      { texto: 'Conferir procedimentos lançados incorretamente.', freq: 'Diário' },
      { texto: 'Conferir ocorrências do dia.', freq: 'Diário' },
      { texto: 'Registrar feedbacks.', freq: 'Diário' },
      { texto: 'Registrar problemas.', freq: 'Diário' },
      { texto: 'Registrar demandas pendentes.', freq: 'Diário' },
      { texto: 'Conferir manutenção pendente.', freq: 'Diário' },
      { texto: 'Conferir compras pendentes.', freq: 'Diário' },
      { texto: 'Conferir organização.', freq: 'Diário' },
      { texto: 'Conferir limpeza.', freq: 'Diário' },
      { texto: 'Conferir materiais.', freq: 'Diário' },
      { texto: 'Conferir agenda do dia seguinte.', freq: 'Diário' },
      { texto: 'Conferir equipe do dia seguinte.', freq: 'Diário' },
      { texto: 'Conferir profissionais suficientes para o dia seguinte.', freq: 'Diário' },
      { texto: 'Conferir grandes grupos do dia seguinte.', freq: 'Diário' },
      { texto: 'Conferir noivas do dia seguinte.', freq: 'Diário' },
      { texto: 'Conferir clientes especiais do dia seguinte.', freq: 'Diário' },
      { texto: 'Comunicar equipe sobre informações importantes.', freq: 'Diário' },
      { texto: 'Enviar lembretes necessários.', freq: 'Diário' },
      { texto: 'Garantir que todas as pendências estejam registradas.', freq: 'Diário' },
    ],
  },
  {
    nome: 'FECHAMENTO DA OCORRÊNCIA',
    itens: [
      { texto: 'Encerrar somente quando — O fato foi identificado.', freq: 'Mensal' },
      { texto: 'Encerrar somente quando — As partes foram ouvidas.', freq: 'Mensal' },
      { texto: 'Encerrar somente quando — Os fatos foram confirmados.', freq: 'Mensal' },
      { texto: 'Encerrar somente quando — O POP foi consultado.', freq: 'Mensal' },
      { texto: 'Encerrar somente quando — O alinhamento foi realizado.', freq: 'Mensal' },
      { texto: 'Encerrar somente quando — A ação corretiva foi definida.', freq: 'Mensal' },
      { texto: 'Encerrar somente quando — O responsável foi definido.', freq: 'Mensal' },
      { texto: 'Encerrar somente quando — O prazo foi definido, quando necessário.', freq: 'Mensal' },
      { texto: 'Encerrar somente quando — A ação foi executada.', freq: 'Mensal' },
      { texto: 'Encerrar somente quando — A melhoria foi acompanhada.', freq: 'Mensal' },
      { texto: 'Encerrar somente quando — O resultado foi validado.', freq: 'Mensal' },
      { texto: 'Encerrar somente quando — O registro foi atualizado.', freq: 'Mensal' },
      { texto: 'Encerrar somente quando — A ocorrência foi encerrada.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'REGRA DE OURO DA COORDENAÇÃO',
    itens: [
      { texto: 'O Coordenador deve — Ouvir antes de decidir.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Orientar antes de cobrar.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Ensinar antes de punir.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Reconhecer antes de criticar.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Agir com equilíbrio.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Manter postura profissional.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Ser imparcial.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Trabalhar com fatos.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Utilizar os POPs como referência.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Preservar o cliente.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Preservar a equipe.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Preservar a cultura.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Preservar a marca.', freq: 'Mensal' },
      { texto: 'O Coordenador deve — Buscar melhoria contínua.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'FECHAMENTO DIÁRIO DO COORDENADOR',
    itens: [
      { texto: 'Antes de encerrar o expediente, responder — O cliente foi bem atendido?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — A equipe está alinhada?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Todos os profissionais cumpriram suas responsabilidades?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve atrasos?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve faltas?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve reclamações?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve conflitos?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve erros de agenda?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve erros de lançamento?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve serviços não realizados?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve problemas financeiros?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve problemas de manutenção?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve problemas de limpeza?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve problemas de estoque?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve algum problema de EPI?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve algum problema técnico?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve algum feedback positivo?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Houve algum feedback negativo?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Tudo foi registrado?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Todas as pendências possuem responsável?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — Todas as pendências possuem prazo?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — A agenda de amanhã está conferida?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — A equipe de amanhã está suficiente?', freq: 'Diário' },
      { texto: 'Antes de encerrar o expediente, responder — A operação de amanhã está preparada?', freq: 'Diário' },
    ],
  },
]
