// Categorias-padrao do CHECK LIST - PROCESSOS & QUALIDADE.
// Gerado a partir do manual do setor. Mesmo padrao dos check lists de
// Manutencao e Coordenacao: uma categoria por bloco, subgrupos viram prefixo
// do item. A ultima categoria (VERIFICACOES DO SALAO) traz os itens que ja
// existiam no check list do setor, com os periodos que eles ja tinham.
// Vive na chave 'checklist_processos'.

export interface CatProcessos { nome: string; itens: { texto: string; freq?: string }[] }

export const CHECKLIST_PROCESSOS: CatProcessos[] = [
  {
    nome: 'GOVERNANÇA DOS PROCESSOS',
    itens: [
      { texto: 'Controle geral — Manter relação oficial de todos os processos da empresa.', freq: 'Mensal' },
      { texto: 'Controle geral — Manter relação oficial de todos os POPs.', freq: 'Mensal' },
      { texto: 'Controle geral — Identificar quais processos possuem POP.', freq: 'Mensal' },
      { texto: 'Controle geral — Identificar processos ainda não documentados.', freq: 'Mensal' },
      { texto: 'Controle geral — Identificar processos duplicados.', freq: 'Mensal' },
      { texto: 'Controle geral — Identificar processos conflitantes.', freq: 'Mensal' },
      { texto: 'Controle geral — Identificar processos desatualizados.', freq: 'Mensal' },
      { texto: 'Controle geral — Identificar processos sem responsável definido.', freq: 'Mensal' },
      { texto: 'Controle geral — Identificar processos sem indicador.', freq: 'Mensal' },
      { texto: 'Controle geral — Identificar processos sem evidência de execução.', freq: 'Mensal' },
      { texto: 'Controle geral — Manter matriz geral de processos.', freq: 'Mensal' },
      { texto: 'Controle geral — Classificar processos por área.', freq: 'Mensal' },
      { texto: 'Controle geral — Classificar processos por criticidade.', freq: 'Mensal' },
      { texto: 'Controle geral — Definir periodicidade de auditoria de cada processo.', freq: 'Mensal' },
      { texto: 'Controle geral — Manter histórico das alterações.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'MAPA DE PROCESSOS DA EMPRESA',
    itens: [
      { texto: 'Mapear processos estratégicos.', freq: 'Mensal' },
      { texto: 'Mapear processos comerciais.', freq: 'Mensal' },
      { texto: 'Mapear processos de atendimento.', freq: 'Mensal' },
      { texto: 'Mapear processos técnicos.', freq: 'Mensal' },
      { texto: 'Mapear processos administrativos.', freq: 'Mensal' },
      { texto: 'Mapear processos financeiros.', freq: 'Mensal' },
      { texto: 'Mapear processos de estoque.', freq: 'Mensal' },
      { texto: 'Mapear processos de compras.', freq: 'Mensal' },
      { texto: 'Mapear processos de limpeza.', freq: 'Mensal' },
      { texto: 'Mapear processos de manutenção.', freq: 'Mensal' },
      { texto: 'Mapear processos de recepção.', freq: 'Mensal' },
      { texto: 'Mapear processos de caixa.', freq: 'Mensal' },
      { texto: 'Mapear processos de pós-venda.', freq: 'Mensal' },
      { texto: 'Mapear processos de experiência do cliente.', freq: 'Mensal' },
      { texto: 'Mapear processos de pessoas quando houver impacto operacional.', freq: 'Mensal' },
      { texto: 'Identificar dependências entre processos.', freq: 'Mensal' },
      { texto: 'Identificar pontos de entrada e saída de cada processo.', freq: 'Mensal' },
      { texto: 'Identificar responsáveis pela execução.', freq: 'Mensal' },
      { texto: 'Identificar pontos críticos de controle.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CADASTRO E CONTROLE DOS POPs',
    itens: [
      { texto: 'Para cada POP — Código.', freq: 'Mensal' },
      { texto: 'Para cada POP — Nome.', freq: 'Mensal' },
      { texto: 'Para cada POP — Área.', freq: 'Mensal' },
      { texto: 'Para cada POP — Objetivo.', freq: 'Mensal' },
      { texto: 'Para cada POP — Aplicação.', freq: 'Mensal' },
      { texto: 'Para cada POP — Responsável.', freq: 'Mensal' },
      { texto: 'Para cada POP — Aprovador.', freq: 'Mensal' },
      { texto: 'Para cada POP — Versão.', freq: 'Mensal' },
      { texto: 'Para cada POP — Data de criação.', freq: 'Mensal' },
      { texto: 'Para cada POP — Data de vigência.', freq: 'Mensal' },
      { texto: 'Para cada POP — Data da última revisão.', freq: 'Mensal' },
      { texto: 'Para cada POP — Próxima revisão.', freq: 'Mensal' },
      { texto: 'Para cada POP — Histórico de alterações.', freq: 'Mensal' },
      { texto: 'Para cada POP — Documentos relacionados.', freq: 'Mensal' },
      { texto: 'Para cada POP — Checklists relacionados.', freq: 'Mensal' },
      { texto: 'Para cada POP — Indicadores relacionados.', freq: 'Mensal' },
      { texto: 'Para cada POP — O controle de versão deve registrar versão, data, alteração e responsável.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CRIAÇÃO DE NOVOS PROCESSOS',
    itens: [
      { texto: 'Quando houver necessidade de criação — Identificar necessidade.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Identificar problema que originou a necessidade.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Levantar informações.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Entender o processo atual.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Mapear etapas.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Identificar responsáveis.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Identificar riscos.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Identificar pontos de controle.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Definir padrão esperado.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Elaborar procedimento.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Criar checklist, quando necessário.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Definir indicadores.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Definir evidências.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Testar o processo.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Identificar falhas do novo processo.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Ajustar documento.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Submeter à aprovação.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Registrar versão oficial.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Definir data de vigência.', freq: 'Mensal' },
      { texto: 'Quando houver necessidade de criação — Publicar versão oficial.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'REVISÃO DE PROCESSOS',
    itens: [
      { texto: 'Verificar processos que atingiram prazo de revisão.', freq: 'Mensal' },
      { texto: 'Revisar processos após ocorrência grave.', freq: 'Mensal' },
      { texto: 'Revisar processos após mudança estrutural.', freq: 'Mensal' },
      { texto: 'Revisar processos após mudança de sistema.', freq: 'Mensal' },
      { texto: 'Revisar processos após alteração de produto.', freq: 'Mensal' },
      { texto: 'Revisar processos após alteração de equipamento.', freq: 'Mensal' },
      { texto: 'Revisar processos após mudança de legislação, quando aplicável.', freq: 'Mensal' },
      { texto: 'Revisar processos com alto índice de erro.', freq: 'Mensal' },
      { texto: 'Revisar processos com alto índice de retrabalho.', freq: 'Mensal' },
      { texto: 'Revisar processos com reclamações recorrentes.', freq: 'Mensal' },
      { texto: 'Revisar processos que geram dúvidas frequentes.', freq: 'Mensal' },
      { texto: 'Registrar necessidade de alteração.', freq: 'Mensal' },
      { texto: 'Atualizar versão.', freq: 'Mensal' },
      { texto: 'Registrar histórico.', freq: 'Mensal' },
      { texto: 'Retirar versão anterior de circulação.', freq: 'Mensal' },
      { texto: 'Garantir que somente a versão vigente permaneça disponível.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CONTROLE DE ALTERAÇÃO DOS PROCESSOS',
    itens: [
      { texto: 'Verificar se houve — Alteração informal de procedimento.', freq: 'Mensal' },
      { texto: 'Verificar se houve — Criação de procedimento paralelo.', freq: 'Mensal' },
      { texto: 'Verificar se houve — Retirada de etapa.', freq: 'Mensal' },
      { texto: 'Verificar se houve — Inclusão de etapa.', freq: 'Mensal' },
      { texto: 'Verificar se houve — Mudança de sequência.', freq: 'Mensal' },
      { texto: 'Verificar se houve — Mudança de roteiro.', freq: 'Mensal' },
      { texto: 'Verificar se houve — Mudança de formulário.', freq: 'Mensal' },
      { texto: 'Verificar se houve — Mudança de checklist.', freq: 'Mensal' },
      { texto: 'Verificar se houve — Mudança de critério.', freq: 'Mensal' },
      { texto: 'Verificar se houve — Mudança de padrão técnico.', freq: 'Mensal' },
      { texto: 'Quando houver alteração não autorizada — Registrar desvio.', freq: 'Mensal' },
      { texto: 'Quando houver alteração não autorizada — Identificar origem.', freq: 'Mensal' },
      { texto: 'Quando houver alteração não autorizada — Identificar impacto.', freq: 'Mensal' },
      { texto: 'Quando houver alteração não autorizada — Restabelecer versão oficial.', freq: 'Mensal' },
      { texto: 'Quando houver alteração não autorizada — Registrar não conformidade.', freq: 'Mensal' },
      { texto: 'Quando houver alteração não autorizada — Avaliar necessidade de ação corretiva.', freq: 'Mensal' },
      { texto: 'Quando houver alteração não autorizada — Avaliar necessidade de revisão do processo.', freq: 'Mensal' },
      { texto: 'Quando houver alteração não autorizada — Regra: alterações em POPs, checklists, roteiros ou procedimentos não devem ser implementadas sem aprovação formal.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'AUDITORIA DE PROCESSOS',
    itens: [
      { texto: 'Preparação — Definir processo a ser auditado.', freq: 'Mensal' },
      { texto: 'Preparação — Definir objetivo da auditoria.', freq: 'Mensal' },
      { texto: 'Preparação — Definir escopo.', freq: 'Mensal' },
      { texto: 'Preparação — Definir período.', freq: 'Mensal' },
      { texto: 'Preparação — Definir critérios.', freq: 'Mensal' },
      { texto: 'Preparação — Separar POP vigente.', freq: 'Mensal' },
      { texto: 'Preparação — Separar checklist de auditoria.', freq: 'Mensal' },
      { texto: 'Preparação — Separar evidências necessárias.', freq: 'Mensal' },
      { texto: 'Preparação — Definir amostra.', freq: 'Mensal' },
      { texto: 'Preparação — Definir responsável pela auditoria.', freq: 'Mensal' },
      { texto: 'Execução — Verificar documentação.', freq: 'Mensal' },
      { texto: 'Execução — Verificar evidências.', freq: 'Mensal' },
      { texto: 'Execução — Verificar registros.', freq: 'Mensal' },
      { texto: 'Execução — Verificar execução conforme padrão.', freq: 'Mensal' },
      { texto: 'Execução — Comparar prática x procedimento oficial.', freq: 'Mensal' },
      { texto: 'Execução — Identificar desvios.', freq: 'Mensal' },
      { texto: 'Execução — Classificar desvios.', freq: 'Mensal' },
      { texto: 'Execução — Registrar evidências.', freq: 'Mensal' },
      { texto: 'Execução — Fotografar/documentar quando aplicável.', freq: 'Mensal' },
      { texto: 'Execução — Registrar data e horário.', freq: 'Mensal' },
      { texto: 'Execução — Identificar área envolvida.', freq: 'Mensal' },
      { texto: 'Execução — Identificar processo relacionado.', freq: 'Mensal' },
      { texto: 'Encerramento — Consolidar resultados.', freq: 'Mensal' },
      { texto: 'Encerramento — Classificar conformidades.', freq: 'Mensal' },
      { texto: 'Encerramento — Classificar não conformidades.', freq: 'Mensal' },
      { texto: 'Encerramento — Identificar pontos de atenção.', freq: 'Mensal' },
      { texto: 'Encerramento — Elaborar relatório.', freq: 'Mensal' },
      { texto: 'Encerramento — Definir ações.', freq: 'Mensal' },
      { texto: 'Encerramento — Definir responsáveis.', freq: 'Mensal' },
      { texto: 'Encerramento — Definir prazos.', freq: 'Mensal' },
      { texto: 'Encerramento — Programar auditoria de verificação.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'AUDITORIA POR AMOSTRAGEM',
    itens: [
      { texto: 'Definir quantidade da amostra.', freq: 'Mensal' },
      { texto: 'Selecionar períodos.', freq: 'Mensal' },
      { texto: 'Selecionar atendimentos.', freq: 'Mensal' },
      { texto: 'Selecionar registros.', freq: 'Mensal' },
      { texto: 'Selecionar profissionais.', freq: 'Mensal' },
      { texto: 'Selecionar documentos.', freq: 'Mensal' },
      { texto: 'Selecionar transações, quando aplicável.', freq: 'Mensal' },
      { texto: 'Evitar seleção tendenciosa.', freq: 'Mensal' },
      { texto: 'Registrar critério utilizado.', freq: 'Mensal' },
      { texto: 'Documentar resultado.', freq: 'Mensal' },
      { texto: 'Comparar percentual de conformidade.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'NÃO CONFORMIDADES',
    itens: [
      { texto: 'Sempre que identificar uma não conformidade — Registrar o fato.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Registrar data.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Registrar local/setor.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Identificar processo.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Identificar POP relacionado.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Descrever o requisito.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Descrever o que foi encontrado.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Registrar evidência.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Classificar gravidade.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Identificar impacto.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Identificar recorrência.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Identificar causa.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Definir ação.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Definir responsável.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Definir prazo.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Acompanhar correção.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Validar eficácia.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Encerrar formalmente.', freq: 'Mensal' },
      { texto: 'Sempre que identificar uma não conformidade — Fluxo oficial: orientação, registro, treinamento, plano de melhoria e escalonamento conforme reincidência.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CLASSIFICAÇÃO DE NÃO CONFORMIDADE',
    itens: [
      { texto: 'LEVE — Falha documental.', freq: 'Mensal' },
      { texto: 'LEVE — Falha de registro.', freq: 'Mensal' },
      { texto: 'LEVE — Pequeno desvio de padrão.', freq: 'Mensal' },
      { texto: 'LEVE — Falha pontual sem impacto relevante.', freq: 'Mensal' },
      { texto: 'MÉDIA — Descumprimento de etapa.', freq: 'Mensal' },
      { texto: 'MÉDIA — Falha recorrente.', freq: 'Mensal' },
      { texto: 'MÉDIA — Erro que gera retrabalho.', freq: 'Mensal' },
      { texto: 'MÉDIA — Erro que impacta experiência.', freq: 'Mensal' },
      { texto: 'MÉDIA — Falha que compromete indicador.', freq: 'Mensal' },
      { texto: 'GRAVE — Risco ao cliente.', freq: 'Mensal' },
      { texto: 'GRAVE — Risco à equipe.', freq: 'Mensal' },
      { texto: 'GRAVE — Descumprimento de procedimento técnico crítico.', freq: 'Mensal' },
      { texto: 'GRAVE — Alteração não autorizada de processo.', freq: 'Mensal' },
      { texto: 'GRAVE — Ocultação de erro.', freq: 'Mensal' },
      { texto: 'GRAVE — Reincidência após ações corretivas.', freq: 'Mensal' },
      { texto: 'GRAVE — Falha com impacto relevante na empresa.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ANÁLISE DE CAUSA RAIZ',
    itens: [
      { texto: 'Para cada problema relevante — Definir exatamente qual é o problema.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Separar sintoma de causa.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Perguntar "por quê?" sucessivamente.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Identificar causa humana.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Identificar causa de processo.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Identificar causa de treinamento.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Identificar causa de sistema.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Identificar causa documental.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Identificar causa de comunicação.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Identificar causa de recurso/material.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Identificar causa estrutural.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Confirmar a causa com evidências.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Evitar atribuir automaticamente culpa ao colaborador.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Definir ação sobre a causa.', freq: 'Mensal' },
      { texto: 'Para cada problema relevante — Validar se a causa foi eliminada.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'PLANO DE AÇÃO — 5W2H',
    itens: [
      { texto: 'Para cada ação — What — O que será feito?', freq: 'Mensal' },
      { texto: 'Para cada ação — Why — Por que será feito?', freq: 'Mensal' },
      { texto: 'Para cada ação — Where — Onde?', freq: 'Mensal' },
      { texto: 'Para cada ação — When — Quando?', freq: 'Mensal' },
      { texto: 'Para cada ação — Who — Quem será responsável?', freq: 'Mensal' },
      { texto: 'Para cada ação — How — Como será feito?', freq: 'Mensal' },
      { texto: 'Para cada ação — How much — Qual custo, quando aplicável?', freq: 'Mensal' },
      { texto: 'Para cada ação — Registrar prazo.', freq: 'Mensal' },
      { texto: 'Para cada ação — Registrar status.', freq: 'Mensal' },
      { texto: 'Para cada ação — Registrar evidência.', freq: 'Mensal' },
      { texto: 'Para cada ação — Validar conclusão.', freq: 'Mensal' },
      { texto: 'Para cada ação — Avaliar eficácia.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CONTROLE DE EFICÁCIA',
    itens: [
      { texto: 'Após uma correção — Verificar se a ação foi realmente executada.', freq: 'Mensal' },
      { texto: 'Após uma correção — Verificar se o problema desapareceu.', freq: 'Mensal' },
      { texto: 'Após uma correção — Verificar se houve reincidência.', freq: 'Mensal' },
      { texto: 'Após uma correção — Comparar indicador antes/depois.', freq: 'Mensal' },
      { texto: 'Após uma correção — Realizar nova amostragem.', freq: 'Mensal' },
      { texto: 'Após uma correção — Avaliar resultado.', freq: 'Mensal' },
      { texto: 'Após uma correção — Confirmar eficácia.', freq: 'Mensal' },
      { texto: 'Após uma correção — Reabrir caso a solução não tenha funcionado.', freq: 'Mensal' },
      { texto: 'Após uma correção — Escalar problema recorrente.', freq: 'Mensal' },
      { texto: 'Após uma correção — Regra: correção concluída não significa problema resolvido.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'INDICADORES DE PROCESSOS',
    itens: [
      { texto: 'Acompanhar mensalmente — % de processos cumpridos.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Índice de conformidade.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Número de não conformidades.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Não conformidades por setor.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Não conformidades por processo.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Não conformidades recorrentes.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Tempo médio de correção.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Taxa de reincidência.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Retrabalho.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Erros operacionais.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Reclamações relacionadas a processo.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Nota média das auditorias.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Índice de padronização.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Treinamentos decorrentes de falhas.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Ações corretivas concluídas.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Ações corretivas atrasadas.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Ações corretivas eficazes.', freq: 'Mensal' },
      { texto: 'Acompanhar mensalmente — Ações corretivas ineficazes.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ANÁLISE DE TENDÊNCIAS',
    itens: [
      { texto: 'Mensalmente — Comparar mês atual x mês anterior.', freq: 'Mensal' },
      { texto: 'Mensalmente — Comparar trimestre.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar aumento de falhas.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar redução de falhas.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar processos críticos.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar setores críticos.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar reincidências.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar horários/períodos críticos.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar causas recorrentes.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar necessidade de mudança estrutural.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar oportunidades de prevenção.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CONTROLE DE RETRABALHO',
    itens: [
      { texto: 'Quantificar retrabalhos.', freq: 'Mensal' },
      { texto: 'Identificar origem.', freq: 'Mensal' },
      { texto: 'Identificar processo relacionado.', freq: 'Mensal' },
      { texto: 'Identificar causa.', freq: 'Mensal' },
      { texto: 'Identificar custo estimado.', freq: 'Mensal' },
      { texto: 'Identificar impacto no tempo.', freq: 'Mensal' },
      { texto: 'Identificar impacto no cliente.', freq: 'Mensal' },
      { texto: 'Identificar reincidência.', freq: 'Mensal' },
      { texto: 'Criar ação preventiva.', freq: 'Mensal' },
      { texto: 'Acompanhar redução.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ANÁLISE DE RECLAMAÇÕES SOB A ÓTICA DE QUALIDADE',
    itens: [
      { texto: 'Catalogar reclamações.', freq: 'Mensal' },
      { texto: 'Classificar reclamações.', freq: 'Mensal' },
      { texto: 'Relacionar reclamação ao processo.', freq: 'Mensal' },
      { texto: 'Identificar recorrência.', freq: 'Mensal' },
      { texto: 'Identificar tendência.', freq: 'Mensal' },
      { texto: 'Identificar causa.', freq: 'Mensal' },
      { texto: 'Verificar se existe POP relacionado.', freq: 'Mensal' },
      { texto: 'Verificar se o POP está adequado.', freq: 'Mensal' },
      { texto: 'Verificar se existe ponto de controle.', freq: 'Mensal' },
      { texto: 'Verificar se existe evidência.', freq: 'Mensal' },
      { texto: 'Avaliar necessidade de alteração do processo.', freq: 'Mensal' },
      { texto: 'Criar ação preventiva.', freq: 'Mensal' },
      { texto: 'Monitorar reincidência.', freq: 'Mensal' },
      { texto: 'Nota: o setor não administra a reclamação no momento em que ela acontece — analisa o problema como dado de qualidade.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'QUALIDADE TÉCNICA DOS PROCESSOS',
    itens: [
      { texto: 'Validar existência de padrão técnico.', freq: 'Mensal' },
      { texto: 'Validar sequência técnica.', freq: 'Mensal' },
      { texto: 'Validar critérios de execução.', freq: 'Mensal' },
      { texto: 'Validar critérios de segurança.', freq: 'Mensal' },
      { texto: 'Validar materiais especificados.', freq: 'Mensal' },
      { texto: 'Validar equipamentos especificados.', freq: 'Mensal' },
      { texto: 'Validar tempo previsto.', freq: 'Mensal' },
      { texto: 'Validar pontos críticos.', freq: 'Mensal' },
      { texto: 'Validar critérios de aprovação.', freq: 'Mensal' },
      { texto: 'Identificar divergências entre POP e prática.', freq: 'Mensal' },
      { texto: 'Atualizar documentação quando necessário.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'QUALIDADE DOS PRODUTOS E INSUMOS',
    itens: [
      { texto: 'Sob a ótica de processo — Verificar se existem padrões definidos para utilização.', freq: 'Mensal' },
      { texto: 'Sob a ótica de processo — Verificar critérios de armazenamento.', freq: 'Mensal' },
      { texto: 'Sob a ótica de processo — Verificar critérios de validade.', freq: 'Mensal' },
      { texto: 'Sob a ótica de processo — Verificar critérios de utilização.', freq: 'Mensal' },
      { texto: 'Sob a ótica de processo — Verificar critérios de descarte.', freq: 'Mensal' },
      { texto: 'Sob a ótica de processo — Verificar produtos incompatíveis com determinado procedimento.', freq: 'Mensal' },
      { texto: 'Sob a ótica de processo — Verificar se existem instruções documentadas.', freq: 'Mensal' },
      { texto: 'Sob a ótica de processo — Auditar cumprimento dos critérios.', freq: 'Mensal' },
      { texto: 'Sob a ótica de processo — Registrar desvios.', freq: 'Mensal' },
      { texto: 'Sob a ótica de processo — Avaliar impacto na qualidade.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'QUALIDADE DE EQUIPAMENTOS',
    itens: [
      { texto: 'Identificar equipamentos críticos.', freq: 'Mensal' },
      { texto: 'Definir padrão mínimo de funcionamento.', freq: 'Mensal' },
      { texto: 'Definir rotina de verificação.', freq: 'Mensal' },
      { texto: 'Definir critérios de indisponibilidade.', freq: 'Mensal' },
      { texto: 'Definir procedimento para equipamento com defeito.', freq: 'Mensal' },
      { texto: 'Auditar cumprimento do processo.', freq: 'Mensal' },
      { texto: 'Registrar falhas recorrentes.', freq: 'Mensal' },
      { texto: 'Avaliar impacto na operação.', freq: 'Mensal' },
      { texto: 'Propor revisão do processo quando necessário.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CONTROLE DE EVIDÊNCIAS',
    itens: [
      { texto: 'Para cada processo crítico — Existe evidência da execução?', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — A evidência é obrigatória?', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Quem registra?', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Onde registra?', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Por quanto tempo permanece registrada?', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — A informação pode ser auditada?', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — O registro é completo?', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — O registro é confiável?', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Existem registros falsos/incompletos?', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Existe risco de perda da informação?', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CHECKLISTS OFICIAIS',
    itens: [
      { texto: 'Criar checklist quando necessário.', freq: 'Mensal' },
      { texto: 'Padronizar perguntas.', freq: 'Mensal' },
      { texto: 'Definir resposta esperada.', freq: 'Mensal' },
      { texto: 'Definir critérios de aprovação.', freq: 'Mensal' },
      { texto: 'Definir campo de evidência.', freq: 'Mensal' },
      { texto: 'Definir responsável pelo preenchimento.', freq: 'Mensal' },
      { texto: 'Definir periodicidade.', freq: 'Mensal' },
      { texto: 'Definir armazenamento.', freq: 'Mensal' },
      { texto: 'Revisar checklist periodicamente.', freq: 'Mensal' },
      { texto: 'Retirar versões antigas.', freq: 'Mensal' },
      { texto: 'Avaliar se o checklist continua útil.', freq: 'Mensal' },
      { texto: 'Eliminar perguntas redundantes.', freq: 'Mensal' },
      { texto: 'Adicionar controles necessários.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'VALIDAÇÃO DOS CHECKLISTS',
    itens: [
      { texto: 'Antes de oficializar — Todas as etapas críticas estão contempladas?', freq: 'Mensal' },
      { texto: 'Antes de oficializar — Existe pergunta desnecessária?', freq: 'Mensal' },
      { texto: 'Antes de oficializar — Existe ambiguidade?', freq: 'Mensal' },
      { texto: 'Antes de oficializar — O item pode ser auditado objetivamente?', freq: 'Mensal' },
      { texto: 'Antes de oficializar — Existe critério claro de conformidade?', freq: 'Mensal' },
      { texto: 'Antes de oficializar — Existe evidência?', freq: 'Mensal' },
      { texto: 'Antes de oficializar — O checklist é executável?', freq: 'Mensal' },
      { texto: 'Antes de oficializar — O checklist gera informação útil?', freq: 'Mensal' },
      { texto: 'Antes de oficializar — O checklist está alinhado ao POP?', freq: 'Mensal' },
      { texto: 'Antes de oficializar — O checklist foi aprovado?', freq: 'Mensal' },
    ],
  },
  {
    nome: 'AUDITORIA DE DOCUMENTAÇÃO',
    itens: [
      { texto: 'Conferir documentos vigentes.', freq: 'Mensal' },
      { texto: 'Conferir documentos vencidos.', freq: 'Mensal' },
      { texto: 'Conferir documentos duplicados.', freq: 'Mensal' },
      { texto: 'Conferir documentos sem aprovação.', freq: 'Mensal' },
      { texto: 'Conferir documentos sem versão.', freq: 'Mensal' },
      { texto: 'Conferir documentos sem responsável.', freq: 'Mensal' },
      { texto: 'Conferir documentos com informações conflitantes.', freq: 'Mensal' },
      { texto: 'Conferir POPs disponíveis à equipe.', freq: 'Mensal' },
      { texto: 'Conferir acesso à versão correta.', freq: 'Mensal' },
      { texto: 'Retirar documentos obsoletos.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'MATRIZ POP x PROCESSO x EVIDÊNCIA',
    itens: [
      { texto: 'Para cada processo — Processo identificado.', freq: 'Mensal' },
      { texto: 'Para cada processo — POP relacionado.', freq: 'Mensal' },
      { texto: 'Para cada processo — Responsável pela execução.', freq: 'Mensal' },
      { texto: 'Para cada processo — Critério de qualidade.', freq: 'Mensal' },
      { texto: 'Para cada processo — Evidência.', freq: 'Mensal' },
      { texto: 'Para cada processo — Indicador.', freq: 'Mensal' },
      { texto: 'Para cada processo — Frequência de auditoria.', freq: 'Mensal' },
      { texto: 'Para cada processo — Última auditoria.', freq: 'Mensal' },
      { texto: 'Para cada processo — Resultado.', freq: 'Mensal' },
      { texto: 'Para cada processo — Próxima auditoria.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'TREINAMENTO DECORRENTE DE PROCESSOS',
    itens: [
      { texto: 'Quando uma falha indicar necessidade de capacitação — Identificar conteúdo.', freq: 'Mensal' },
      { texto: 'Quando uma falha indicar necessidade de capacitação — Identificar público.', freq: 'Mensal' },
      { texto: 'Quando uma falha indicar necessidade de capacitação — Identificar causa.', freq: 'Mensal' },
      { texto: 'Quando uma falha indicar necessidade de capacitação — Preparar material.', freq: 'Mensal' },
      { texto: 'Quando uma falha indicar necessidade de capacitação — Realizar treinamento.', freq: 'Mensal' },
      { texto: 'Quando uma falha indicar necessidade de capacitação — Registrar participantes.', freq: 'Mensal' },
      { texto: 'Quando uma falha indicar necessidade de capacitação — Aplicar avaliação, quando necessário.', freq: 'Mensal' },
      { texto: 'Quando uma falha indicar necessidade de capacitação — Validar entendimento.', freq: 'Mensal' },
      { texto: 'Quando uma falha indicar necessidade de capacitação — Fazer nova auditoria.', freq: 'Mensal' },
      { texto: 'Quando uma falha indicar necessidade de capacitação — Verificar se o erro diminuiu.', freq: 'Mensal' },
      { texto: 'Quando uma falha indicar necessidade de capacitação — Nota: aqui o treinamento corrige falha de padronização, não é gestão cotidiana da equipe.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ANÁLISE DE NOVOS PROCESSOS ANTES DA IMPLANTAÇÃO',
    itens: [
      { texto: 'Antes de liberar — Processo está documentado?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Responsáveis definidos?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Etapas claras?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Riscos identificados?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Pontos críticos definidos?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Evidências definidas?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Indicadores definidos?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Checklist criado?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Treinamento necessário identificado?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Teste realizado?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Resultado do teste aprovado?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Documento aprovado?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Versão registrada?', freq: 'Mensal' },
      { texto: 'Antes de liberar — Data de vigência definida?', freq: 'Mensal' },
    ],
  },
  {
    nome: 'MELHORIA CONTÍNUA',
    itens: [
      { texto: 'Receber sugestões de — Colaboradores.', freq: 'Mensal' },
      { texto: 'Receber sugestões de — Gestores.', freq: 'Mensal' },
      { texto: 'Receber sugestões de — Clientes.', freq: 'Mensal' },
      { texto: 'Receber sugestões de — Auditorias.', freq: 'Mensal' },
      { texto: 'Receber sugestões de — Indicadores.', freq: 'Mensal' },
      { texto: 'Receber sugestões de — Reclamações.', freq: 'Mensal' },
      { texto: 'Receber sugestões de — Retrabalhos.', freq: 'Mensal' },
      { texto: 'Receber sugestões de — Não conformidades.', freq: 'Mensal' },
      { texto: 'Receber sugestões de — Análises de causa.', freq: 'Mensal' },
      { texto: 'Receber sugestões de — Resultados financeiros relacionados a processos.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Registrar.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Avaliar.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Identificar benefício.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Identificar risco.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Testar quando aplicável.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Medir resultado.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Aprovar.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Documentar.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Atualizar POP.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Atualizar checklist.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Comunicar alteração.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Arquivar versão anterior.', freq: 'Mensal' },
      { texto: 'Para cada sugestão — Regra: todos podem sugerir, mas nenhuma mudança entra no processo antes de testada, documentada, aprovada e incorporada ao POP.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CONTROLE DE RISCOS DE PROCESSO',
    itens: [
      { texto: 'Para cada processo crítico — Identificar risco.', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Identificar probabilidade.', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Identificar impacto.', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Classificar criticidade.', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Identificar controle existente.', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Verificar se o controle funciona.', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Identificar ausência de controle.', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Criar ação preventiva.', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Monitorar risco.', freq: 'Mensal' },
      { texto: 'Para cada processo crítico — Reavaliar periodicamente.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'PROCESSOS CRÍTICOS',
    itens: [
      { texto: 'CRÍTICO — Segurança.', freq: 'Mensal' },
      { texto: 'CRÍTICO — Saúde/higiene.', freq: 'Mensal' },
      { texto: 'CRÍTICO — Processos técnicos de alto risco.', freq: 'Mensal' },
      { texto: 'CRÍTICO — Processos com impacto financeiro elevado.', freq: 'Mensal' },
      { texto: 'CRÍTICO — Processos com impacto jurídico.', freq: 'Mensal' },
      { texto: 'CRÍTICO — Processos com alto impacto na imagem.', freq: 'Mensal' },
      { texto: 'IMPORTANTE — Processos que geram retrabalho.', freq: 'Mensal' },
      { texto: 'IMPORTANTE — Processos que afetam produtividade.', freq: 'Mensal' },
      { texto: 'IMPORTANTE — Processos que afetam experiência.', freq: 'Mensal' },
      { texto: 'PADRÃO — Processos administrativos de menor impacto.', freq: 'Mensal' },
      { texto: 'PADRÃO — Rotinas de suporte.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'AUDITORIA ESPECIAL',
    itens: [
      { texto: 'Realizar auditoria extraordinária quando ocorrer — Reclamação grave.', freq: 'Mensal' },
      { texto: 'Realizar auditoria extraordinária quando ocorrer — Falha técnica grave.', freq: 'Mensal' },
      { texto: 'Realizar auditoria extraordinária quando ocorrer — Acidente.', freq: 'Mensal' },
      { texto: 'Realizar auditoria extraordinária quando ocorrer — Grande volume de retrabalho.', freq: 'Mensal' },
      { texto: 'Realizar auditoria extraordinária quando ocorrer — Aumento inesperado de erros.', freq: 'Mensal' },
      { texto: 'Realizar auditoria extraordinária quando ocorrer — Reincidência.', freq: 'Mensal' },
      { texto: 'Realizar auditoria extraordinária quando ocorrer — Alteração de processo.', freq: 'Mensal' },
      { texto: 'Realizar auditoria extraordinária quando ocorrer — Alteração de sistema.', freq: 'Mensal' },
      { texto: 'Realizar auditoria extraordinária quando ocorrer — Alteração de equipamento.', freq: 'Mensal' },
      { texto: 'Realizar auditoria extraordinária quando ocorrer — Mudança relevante de operação.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'RELATÓRIO DE QUALIDADE',
    itens: [
      { texto: 'Mensalmente preparar — Total de auditorias.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Total de processos auditados.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Índice de conformidade.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Total de não conformidades.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Não conformidades por gravidade.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Não conformidades por setor.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Não conformidades por processo.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Reincidências.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Retrabalhos.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Reclamações relacionadas a processos.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Tempo médio de correção.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Ações pendentes.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Ações concluídas.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Ações eficazes.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Ações ineficazes.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Treinamentos realizados.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Processos revisados.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — POPs criados.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — POPs alterados.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Principais riscos.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Principais oportunidades.', freq: 'Mensal' },
      { texto: 'Mensalmente preparar — Plano de ação do próximo período.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'APRESENTAÇÃO À DIREÇÃO',
    itens: [
      { texto: 'Apresentar — Evolução do índice de conformidade.', freq: 'Mensal' },
      { texto: 'Apresentar — Evolução das não conformidades.', freq: 'Mensal' },
      { texto: 'Apresentar — Processos mais problemáticos.', freq: 'Mensal' },
      { texto: 'Apresentar — Processos que melhoraram.', freq: 'Mensal' },
      { texto: 'Apresentar — Principais causas.', freq: 'Mensal' },
      { texto: 'Apresentar — Principais riscos.', freq: 'Mensal' },
      { texto: 'Apresentar — Retrabalho gerado.', freq: 'Mensal' },
      { texto: 'Apresentar — Reclamações relacionadas a processos.', freq: 'Mensal' },
      { texto: 'Apresentar — Ações corretivas.', freq: 'Mensal' },
      { texto: 'Apresentar — Resultados das ações.', freq: 'Mensal' },
      { texto: 'Apresentar — Necessidades de mudança.', freq: 'Mensal' },
      { texto: 'Apresentar — Necessidades de investimento.', freq: 'Mensal' },
      { texto: 'Apresentar — Necessidades de treinamento.', freq: 'Mensal' },
      { texto: 'Apresentar — Recomendações de melhoria.', freq: 'Mensal' },
      { texto: 'Apresentar — Nota: apresentar informação de sistema, não apenas acontecimentos.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CONTROLE DE PRAZOS',
    itens: [
      { texto: 'Auditorias vencidas.', freq: 'Semanal' },
      { texto: 'Auditorias próximas do vencimento.', freq: 'Semanal' },
      { texto: 'POPs para revisão.', freq: 'Semanal' },
      { texto: 'Ações corretivas vencidas.', freq: 'Semanal' },
      { texto: 'Planos de melhoria vencidos.', freq: 'Semanal' },
      { texto: 'Treinamentos pendentes.', freq: 'Semanal' },
      { texto: 'Validações pendentes.', freq: 'Semanal' },
      { texto: 'Aprovações pendentes.', freq: 'Semanal' },
      { texto: 'Alterações aguardando aprovação.', freq: 'Semanal' },
    ],
  },
  {
    nome: 'CONTROLE DE RECORRÊNCIA',
    itens: [
      { texto: 'Sempre que um problema aparecer novamente — Localizar ocorrência anterior.', freq: 'Mensal' },
      { texto: 'Sempre que um problema aparecer novamente — Comparar causas.', freq: 'Mensal' },
      { texto: 'Sempre que um problema aparecer novamente — Verificar ação anterior.', freq: 'Mensal' },
      { texto: 'Sempre que um problema aparecer novamente — Verificar se ação foi concluída.', freq: 'Mensal' },
      { texto: 'Sempre que um problema aparecer novamente — Verificar se ação foi eficaz.', freq: 'Mensal' },
      { texto: 'Sempre que um problema aparecer novamente — Identificar falha da ação anterior.', freq: 'Mensal' },
      { texto: 'Sempre que um problema aparecer novamente — Reavaliar causa raiz.', freq: 'Mensal' },
      { texto: 'Sempre que um problema aparecer novamente — Criar nova ação.', freq: 'Mensal' },
      { texto: 'Sempre que um problema aparecer novamente — Escalar criticidade.', freq: 'Mensal' },
      { texto: 'Sempre que um problema aparecer novamente — Comunicar Gerência quando necessário.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'AUDITORIA DE EXPERIÊNCIA DO CLIENTE',
    itens: [
      { texto: 'Verificar conformidade ao padrão — Existe roteiro de atendimento?', freq: 'Mensal' },
      { texto: 'Verificar conformidade ao padrão — O roteiro está documentado?', freq: 'Mensal' },
      { texto: 'Verificar conformidade ao padrão — O roteiro está atualizado?', freq: 'Mensal' },
      { texto: 'Verificar conformidade ao padrão — As etapas estão sendo cumpridas?', freq: 'Mensal' },
      { texto: 'Verificar conformidade ao padrão — Existem pontos de quebra?', freq: 'Mensal' },
      { texto: 'Verificar conformidade ao padrão — Existem reclamações relacionadas?', freq: 'Mensal' },
      { texto: 'Verificar conformidade ao padrão — Existe evidência?', freq: 'Mensal' },
      { texto: 'Verificar conformidade ao padrão — O padrão é reproduzível?', freq: 'Mensal' },
      { texto: 'Verificar conformidade ao padrão — O processo precisa ser revisado?', freq: 'Mensal' },
      { texto: 'Verificar conformidade ao padrão — Nota: não substitui a Coordenação — verifica se o processo desenhado produz o padrão esperado.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'AUDITORIA DE RECEPÇÃO',
    itens: [
      { texto: 'Avaliar o processo, não a pessoa — Existe roteiro?', freq: 'Mensal' },
      { texto: 'Avaliar o processo, não a pessoa — Existe padrão de comunicação?', freq: 'Mensal' },
      { texto: 'Avaliar o processo, não a pessoa — Existe fluxo documentado?', freq: 'Mensal' },
      { texto: 'Avaliar o processo, não a pessoa — Existem critérios de agendamento?', freq: 'Mensal' },
      { texto: 'Avaliar o processo, não a pessoa — Existem critérios para alterações?', freq: 'Mensal' },
      { texto: 'Avaliar o processo, não a pessoa — Existem critérios para cancelamentos?', freq: 'Mensal' },
      { texto: 'Avaliar o processo, não a pessoa — Existem critérios para encaixes?', freq: 'Mensal' },
      { texto: 'Avaliar o processo, não a pessoa — Existem critérios para confirmação?', freq: 'Mensal' },
      { texto: 'Avaliar o processo, não a pessoa — Existem critérios para registro?', freq: 'Mensal' },
      { texto: 'Avaliar o processo, não a pessoa — O processo é seguido?', freq: 'Mensal' },
      { texto: 'Avaliar o processo, não a pessoa — Onde estão ocorrendo falhas?', freq: 'Mensal' },
      { texto: 'Avaliar o processo, não a pessoa — Qual a causa?', freq: 'Mensal' },
      { texto: 'Avaliar o processo, não a pessoa — O processo precisa ser melhorado?', freq: 'Mensal' },
    ],
  },
  {
    nome: 'AUDITORIA DE CAIXA E PROCESSOS FINANCEIROS',
    itens: [
      { texto: 'Verificar existência de procedimento.', freq: 'Mensal' },
      { texto: 'Verificar sequência definida.', freq: 'Mensal' },
      { texto: 'Verificar critérios de conferência.', freq: 'Mensal' },
      { texto: 'Verificar registros.', freq: 'Mensal' },
      { texto: 'Verificar evidências.', freq: 'Mensal' },
      { texto: 'Verificar divergências.', freq: 'Mensal' },
      { texto: 'Verificar reincidência.', freq: 'Mensal' },
      { texto: 'Identificar ponto de falha.', freq: 'Mensal' },
      { texto: 'Avaliar risco.', freq: 'Mensal' },
      { texto: 'Propor correção de processo.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'AUDITORIA DE ESTOQUE',
    itens: [
      { texto: 'Verificar procedimento de entrada.', freq: 'Mensal' },
      { texto: 'Verificar procedimento de saída.', freq: 'Mensal' },
      { texto: 'Verificar armazenamento.', freq: 'Mensal' },
      { texto: 'Verificar identificação.', freq: 'Mensal' },
      { texto: 'Verificar validade.', freq: 'Mensal' },
      { texto: 'Verificar critérios de controle.', freq: 'Mensal' },
      { texto: 'Verificar registros.', freq: 'Mensal' },
      { texto: 'Verificar divergências.', freq: 'Mensal' },
      { texto: 'Verificar perdas.', freq: 'Mensal' },
      { texto: 'Verificar desperdícios.', freq: 'Mensal' },
      { texto: 'Verificar rastreabilidade quando aplicável.', freq: 'Mensal' },
      { texto: 'Identificar falhas do processo.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'AUDITORIA DE LIMPEZA E HIGIENE',
    itens: [
      { texto: 'O padrão está definido? — Existe POP?', freq: 'Mensal' },
      { texto: 'O padrão está definido? — Existe frequência definida?', freq: 'Mensal' },
      { texto: 'O padrão está definido? — Existe responsável?', freq: 'Mensal' },
      { texto: 'O padrão está definido? — Existe checklist?', freq: 'Mensal' },
      { texto: 'O padrão está definido? — Existe critério de aprovação?', freq: 'Mensal' },
      { texto: 'O padrão está definido? — Existe evidência?', freq: 'Mensal' },
      { texto: 'O padrão está definido? — Existe auditoria?', freq: 'Mensal' },
      { texto: 'O padrão está definido? — O padrão é cumprido?', freq: 'Mensal' },
      { texto: 'O padrão está definido? — Existem reincidências?', freq: 'Mensal' },
      { texto: 'O padrão está definido? — O processo precisa ser alterado?', freq: 'Mensal' },
    ],
  },
  {
    nome: 'AUDITORIA DE PÓS-VENDA',
    itens: [
      { texto: 'Existe processo formal?', freq: 'Mensal' },
      { texto: 'Existe prazo?', freq: 'Mensal' },
      { texto: 'Existe roteiro?', freq: 'Mensal' },
      { texto: 'Existe registro?', freq: 'Mensal' },
      { texto: 'Existe responsável?', freq: 'Mensal' },
      { texto: 'Existe critério de contato?', freq: 'Mensal' },
      { texto: 'Existe evidência?', freq: 'Mensal' },
      { texto: 'Existe medição?', freq: 'Mensal' },
      { texto: 'O processo está sendo cumprido?', freq: 'Mensal' },
      { texto: 'O processo gera resultado?', freq: 'Mensal' },
      { texto: 'Existem pontos de melhoria?', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CONTROLE DE PADRONIZAÇÃO',
    itens: [
      { texto: 'Mensalmente — Medir aderência aos POPs.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar áreas com maior aderência.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar áreas com menor aderência.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar processos com maior variação.', freq: 'Mensal' },
      { texto: 'Mensalmente — Identificar causas de variação.', freq: 'Mensal' },
      { texto: 'Mensalmente — Criar ações.', freq: 'Mensal' },
      { texto: 'Mensalmente — Reavaliar.', freq: 'Mensal' },
      { texto: 'Mensalmente — Objetivo: execução padronizada dos serviços, redução de erros e retrabalho e melhoria contínua.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ENCERRAMENTO DE AUDITORIA',
    itens: [
      { texto: 'Nenhuma auditoria encerrada sem — Resultado registrado.', freq: 'Mensal' },
      { texto: 'Nenhuma auditoria encerrada sem — Evidências arquivadas.', freq: 'Mensal' },
      { texto: 'Nenhuma auditoria encerrada sem — Não conformidades classificadas.', freq: 'Mensal' },
      { texto: 'Nenhuma auditoria encerrada sem — Causas identificadas.', freq: 'Mensal' },
      { texto: 'Nenhuma auditoria encerrada sem — Ações definidas.', freq: 'Mensal' },
      { texto: 'Nenhuma auditoria encerrada sem — Responsáveis definidos.', freq: 'Mensal' },
      { texto: 'Nenhuma auditoria encerrada sem — Prazos definidos.', freq: 'Mensal' },
      { texto: 'Nenhuma auditoria encerrada sem — Acompanhamento programado.', freq: 'Mensal' },
      { texto: 'Nenhuma auditoria encerrada sem — Eficácia validada.', freq: 'Mensal' },
      { texto: 'Nenhuma auditoria encerrada sem — Relatório concluído.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CHECKLIST MENSAL DO SETOR',
    itens: [
      { texto: 'Documentação — Todos os POPs estão atualizados?', freq: 'Mensal' },
      { texto: 'Documentação — Existe algum POP vencido?', freq: 'Mensal' },
      { texto: 'Documentação — Existem processos sem documentação?', freq: 'Mensal' },
      { texto: 'Documentação — Existem documentos duplicados?', freq: 'Mensal' },
      { texto: 'Documentação — Todas as versões estão controladas?', freq: 'Mensal' },
      { texto: 'Auditoria — Auditorias previstas foram realizadas?', freq: 'Mensal' },
      { texto: 'Auditoria — Todas possuem evidências?', freq: 'Mensal' },
      { texto: 'Auditoria — Todas as não conformidades foram registradas?', freq: 'Mensal' },
      { texto: 'Auditoria — Todas possuem classificação?', freq: 'Mensal' },
      { texto: 'Melhoria — Ações corretivas foram executadas?', freq: 'Mensal' },
      { texto: 'Melhoria — Ações foram eficazes?', freq: 'Mensal' },
      { texto: 'Melhoria — Existem reincidências?', freq: 'Mensal' },
      { texto: 'Melhoria — Existem processos que precisam ser redesenhados?', freq: 'Mensal' },
      { texto: 'Indicadores — Índice de conformidade atualizado?', freq: 'Mensal' },
      { texto: 'Indicadores — Não conformidades atualizadas?', freq: 'Mensal' },
      { texto: 'Indicadores — Retrabalho atualizado?', freq: 'Mensal' },
      { texto: 'Indicadores — Reclamações analisadas?', freq: 'Mensal' },
      { texto: 'Indicadores — Tempo de correção calculado?', freq: 'Mensal' },
      { texto: 'Indicadores — Reincidência calculada?', freq: 'Mensal' },
      { texto: 'Indicadores — Auditorias consolidadas?', freq: 'Mensal' },
      { texto: 'Documentação para Direção — Relatório mensal concluído?', freq: 'Mensal' },
      { texto: 'Documentação para Direção — Principais problemas identificados?', freq: 'Mensal' },
      { texto: 'Documentação para Direção — Principais causas identificadas?', freq: 'Mensal' },
      { texto: 'Documentação para Direção — Plano de ação definido?', freq: 'Mensal' },
      { texto: 'Documentação para Direção — Recomendações elaboradas?', freq: 'Mensal' },
    ],
  },
  {
    nome: 'CHECKLIST DE SAÍDA DO ANALISTA DE PROCESSOS',
    itens: [
      { texto: 'Antes de encerrar o ciclo — Nenhuma auditoria sem conclusão.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Nenhuma não conformidade sem classificação.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Nenhuma ação sem responsável.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Nenhuma ação sem prazo.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Nenhuma ação vencida sem justificativa.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Nenhum POP crítico sem revisão programada.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Nenhuma alteração de processo sem controle.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Nenhuma versão antiga em circulação.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Nenhum problema recorrente sem análise de causa.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Nenhum indicador crítico sem análise.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Nenhum resultado relevante sem evidência.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Relatório atualizado.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Plano de ação atualizado.', freq: 'Mensal' },
      { texto: 'Antes de encerrar o ciclo — Próximas auditorias programadas.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'PRINCÍPIO DE ATUAÇÃO — PROCESSOS & QUALIDADE',
    itens: [
      { texto: 'Sequência de trabalho — 1. PADRÃO', freq: 'Mensal' },
      { texto: 'Sequência de trabalho — 2. MEDIÇÃO', freq: 'Mensal' },
      { texto: 'Sequência de trabalho — 3. AUDITORIA', freq: 'Mensal' },
      { texto: 'Sequência de trabalho — 4. DESVIO', freq: 'Mensal' },
      { texto: 'Sequência de trabalho — 5. CAUSA', freq: 'Mensal' },
      { texto: 'Sequência de trabalho — 6. AÇÃO CORRETIVA', freq: 'Mensal' },
      { texto: 'Sequência de trabalho — 7. VALIDAÇÃO', freq: 'Mensal' },
      { texto: 'Sequência de trabalho — 8. MELHORIA', freq: 'Mensal' },
      { texto: 'Sequência de trabalho — 9. NOVO PADRÃO', freq: 'Mensal' },
    ],
  },
  {
    nome: 'O QUE NÃO PERTENCE AO SETOR',
    itens: [
      { texto: 'Não assumir como rotina — Montar escala diária.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Cobrir falta de profissional.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Redistribuir atendimento.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Administrar a agenda do dia.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Resolver conflito pessoal no momento em que ocorre.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Fazer gestão cotidiana da equipe.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Cobrar produtividade individual diariamente.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Organizar a rotina do salão.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Gerenciar o fluxo de clientes.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Fazer acolhimento operacional.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Substituir recepção.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Fazer atendimento de cliente.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Autorizar desconto comercial.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Decidir férias.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Definir folgas.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Gerenciar o funcionamento diário do salão.', freq: 'Mensal' },
      { texto: 'Não assumir como rotina — Função do setor: verificar se existe processo adequado, se está documentado, se é cumprido, se produz o resultado esperado e, quando não produz, por quê e como melhorar.', freq: 'Mensal' },
    ],
  },
  {
    nome: 'VERIFICAÇÕES DO SALÃO',
    itens: [
      { texto: 'JARDIM - VERIFICAR SE O RESERVATORIO DE ÁGUA DO PAINEL TA CHEIO', freq: 'Diário' },
      { texto: 'VESTIMENTA - VERIFICAR A COR E MODELO DE ROUPA DE TODOS OS PROFISSIONAIS PRETO BRANCA CINZA OU BEGE NÃO PODE REGATA E NEM SAIAS COM FENDAS GRANDE ( MANICURES SANDALIAS FECHADOS)', freq: 'Diário' },
      { texto: 'EPI - VERIFICAR SE TODAS AS MANICURES ESTÃO USANDO MÁSCARAS', freq: 'Diário' },
      { texto: 'EPI - VERIFICAR QUEM ESTA ESTERELIZANDO ALICATES E PINÇAS', freq: 'Diário' },
      { texto: 'EPI - VERIFICAR QUEM NÃO TA PEDINDO KITS MANICURES E PEDICURES SUFICIENTES', freq: 'Diário' },
      { texto: 'COMPRAS - VERIFICAR SE NA DOSAGEM ESTA FALTANDO ALGUMA COISA ( Fazer um check list e colocar aqui)', freq: 'Diário' },
      { texto: 'COMPRAS CAFÉ - SOLICISTAR A COMPRA ( GRÃO , AÇUCAR , MECHEDOR , CAPUCCINO , CHÁS , COCA, SUCO, BISCOITO DE QUEIJO , GELO , VINHOS TINTO, VINHOS SECO, CERVEJA , BOLOS, DESCARTAVEIS (COPO, COLHER, PRATO), VELA DE ANIVERSÁRIO , COPO DE AGUA VIDROS , XICARAS , PIRES , GUARDA NAPO , POTES DESCARTAVEIS , COLHER DE FERRO.', freq: 'Diário' },
      { texto: 'vrificar o chek lista da limpeza do salçai', freq: 'Diário' },
      { texto: 'VITRINES - VERIFICAR SE ESTÃO LIMPAS E ALINHADAS', freq: 'Diário' },
      { texto: 'Verificar se tem água no reservatório', freq: 'Diário' },
      { texto: 'Verificar se a dosagem precisa de algo', freq: 'Diário' },
      { texto: 'Verificar se a recepção precisa de algo', freq: 'Diário' },
      { texto: 'Verificar o check list da limpeza do salão', freq: 'Diário' },
      { texto: 'ver com a recepção e limpeza se precisa de algo', freq: 'Diário' },
      { texto: 'Ver imagem pessoal de todos', freq: 'Diário' },
      { texto: 'verificar a limpeza do salão pegar o check list da limpeza e verificar passar o fino', freq: 'Diário' },
      { texto: 'Verificar a limpeza do salão: pegar o check list da limpeza e verificar, passar o fino', freq: 'Diário' },
      { texto: 'Verificar com a Dosadora o que precisa comprar e o que precisa ser ajustado', freq: 'Diário' },
      { texto: 'VERIFICAR SE AS MANICURES ESTÃO USANDO TOALHAS DELAS OU DO SALÃO', freq: 'Diário' },
      { texto: 'TODOS OS PROFISSIONAIS HIGIENIZARAM AS ESCOVAS PARA O ATENDIMENTO DO DIA ?', freq: 'Diário' },
      { texto: 'JARDIM - MOLHAR AS PLANTAS INTERNAS E EXTERNAS 2X NA SEMANA', freq: 'Semanal' },
      { texto: 'CHECK LISTA DA DOSAGEM - Conferir se foi feito todos', freq: 'Semanal' },
      { texto: 'Escala de Domingo - Ajustar desfalques com outro profissional, se necessário', freq: 'Semanal' },
      { texto: 'verificar todos o ponto da lista do código do consumidor', freq: 'Mensal' },
      { texto: 'ARQUIVAR DOCUMENTOS - PEGAR OS DOCUMENTOS DA SALA DA BRUNA E ARQUIVAR NO ESTOQUE.', freq: 'Mensal' },
      { texto: 'COMPRAS - VERIFICAR SE TEM QUE COMPRAR MATERIAR DE ESCRITORIO ( RESMA, CANETAS , BOBINAS , ETIQUETAS DE PREÇO , TINTA DAS ETIQUETAS DE PREÇO, LAPIS, BORRACHAS, MARCA TEXTOS , GRAMPOS , CLIPS , TESOURA , DUREX', freq: 'Mensal' },
    ],
  },
]
