// Categorias-padrao do CHECK LIST - MANUTENCAO PREDIAL do setor Manutencao.
// Gerado a partir do roteiro de inspecao enviado pelo salao. Os itens nascem
// com periodo MENSAL (inspecao de rotina) - da para mudar item a item no Editar,
// alem de adicionar/excluir categorias e itens. Vive na chave 'checklist_manutencao',
// separado do check list diario do salao.

export interface CatManutencao { nome: string; itens: { texto: string; freq?: string }[] }

export const CHECKLIST_MANUTENCAO: CatManutencao[] = [
  {
    nome: 'ESTRUTURA FÍSICA / PREDIAL',
    itens: [
      { texto: 'Paredes — rachaduras', freq: 'Mensal' },
      { texto: 'Paredes — trincas', freq: 'Mensal' },
      { texto: 'Paredes — infiltrações', freq: 'Mensal' },
      { texto: 'Paredes — umidade', freq: 'Mensal' },
      { texto: 'Paredes — descascamento da pintura', freq: 'Mensal' },
      { texto: 'Paredes — mofo', freq: 'Mensal' },
      { texto: 'Paredes — revestimentos soltos', freq: 'Mensal' },
      { texto: 'Paredes — azulejos quebrados', freq: 'Mensal' },
      { texto: 'Paredes — azulejos soltos', freq: 'Mensal' },
      { texto: 'Paredes — rejuntes deteriorados', freq: 'Mensal' },
      { texto: 'Paredes — acabamento das paredes', freq: 'Mensal' },
      { texto: 'Paredes — quinas e cantos danificados', freq: 'Mensal' },
      { texto: 'Tetos / forros — manchas de infiltração', freq: 'Mensal' },
      { texto: 'Tetos / forros — placas de forro', freq: 'Mensal' },
      { texto: 'Tetos / forros — forro solto', freq: 'Mensal' },
      { texto: 'Tetos / forros — rachaduras', freq: 'Mensal' },
      { texto: 'Tetos / forros — pintura', freq: 'Mensal' },
      { texto: 'Tetos / forros — sinais de vazamento', freq: 'Mensal' },
      { texto: 'Tetos / forros — pontos próximos a luminárias', freq: 'Mensal' },
      { texto: 'Tetos / forros — estruturas aparentes', freq: 'Mensal' },
      { texto: 'Pisos — peças quebradas', freq: 'Mensal' },
      { texto: 'Pisos — peças soltas', freq: 'Mensal' },
      { texto: 'Pisos — desníveis', freq: 'Mensal' },
      { texto: 'Pisos — rachaduras', freq: 'Mensal' },
      { texto: 'Pisos — rejuntes', freq: 'Mensal' },
      { texto: 'Pisos — pisos escorregadios', freq: 'Mensal' },
      { texto: 'Pisos — rodapés', freq: 'Mensal' },
      { texto: 'Pisos — acabamento', freq: 'Mensal' },
      { texto: 'Pisos — risco de tropeço', freq: 'Mensal' },
    ],
  },
  {
    nome: 'PORTAS, JANELAS E VIDROS',
    itens: [
      { texto: 'Portas — Abrindo corretamente', freq: 'Mensal' },
      { texto: 'Portas — Fechando corretamente', freq: 'Mensal' },
      { texto: 'Portas — Dobradiças funcionando', freq: 'Mensal' },
      { texto: 'Portas — Fechaduras funcionando', freq: 'Mensal' },
      { texto: 'Portas — Maçanetas firmes', freq: 'Mensal' },
      { texto: 'Portas — Batentes íntegros', freq: 'Mensal' },
      { texto: 'Portas — Mola aérea funcionando, quando houver', freq: 'Mensal' },
      { texto: 'Portas — Amortecedor funcionando', freq: 'Mensal' },
      { texto: 'Portas — Porta sem empenamento', freq: 'Mensal' },
      { texto: 'Portas — Porta sem ruídos anormais', freq: 'Mensal' },
      { texto: 'Janelas — Abertura funcionando', freq: 'Mensal' },
      { texto: 'Janelas — Fechamento funcionando', freq: 'Mensal' },
      { texto: 'Janelas — Travas funcionando', freq: 'Mensal' },
      { texto: 'Janelas — Trilhos funcionando', freq: 'Mensal' },
      { texto: 'Janelas — Vidros íntegros', freq: 'Mensal' },
      { texto: 'Janelas — Vedação adequada', freq: 'Mensal' },
      { texto: 'Janelas — Sem infiltração', freq: 'Mensal' },
      { texto: 'Vidros / espelhos — Espelhos sem trincas', freq: 'Mensal' },
      { texto: 'Vidros / espelhos — Espelhos firmes', freq: 'Mensal' },
      { texto: 'Vidros / espelhos — Fixações seguras', freq: 'Mensal' },
      { texto: 'Vidros / espelhos — Vidros sem trincas', freq: 'Mensal' },
      { texto: 'Vidros / espelhos — Películas íntegras', freq: 'Mensal' },
      { texto: 'Vidros / espelhos — Estrutura de sustentação adequada', freq: 'Mensal' },
    ],
  },
  {
    nome: 'INSTALAÇÃO ELÉTRICA',
    itens: [
      { texto: 'Tomadas funcionando', freq: 'Mensal' },
      { texto: 'Interruptores funcionando', freq: 'Mensal' },
      { texto: 'Espelhos das tomadas íntegros', freq: 'Mensal' },
      { texto: 'Tomadas sem aquecimento anormal', freq: 'Mensal' },
      { texto: 'Tomadas sem faíscas', freq: 'Mensal' },
      { texto: 'Cabos sem exposição', freq: 'Mensal' },
      { texto: 'Fiação sem danos aparentes', freq: 'Mensal' },
      { texto: 'Quadros elétricos identificados', freq: 'Mensal' },
      { texto: 'Disjuntores identificados', freq: 'Mensal' },
      { texto: 'Quadro sem sinais de aquecimento', freq: 'Mensal' },
      { texto: 'Quadro sem cheiro de queimado', freq: 'Mensal' },
      { texto: 'Circuitos identificados', freq: 'Mensal' },
      { texto: 'Dispositivos de proteção adequados e em condição de uso', freq: 'Mensal' },
      { texto: 'Extensões verificadas', freq: 'Mensal' },
      { texto: 'Filtros de linha verificados', freq: 'Mensal' },
      { texto: 'Cabos organizados', freq: 'Mensal' },
      { texto: 'Sem sobrecarga de tomadas', freq: 'Mensal' },
      { texto: 'Equipamentos ligados em pontos adequados', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ILUMINAÇÃO',
    itens: [
      { texto: 'Lâmpadas funcionando', freq: 'Mensal' },
      { texto: 'Luminárias funcionando', freq: 'Mensal' },
      { texto: 'Spots funcionando', freq: 'Mensal' },
      { texto: 'Pendentes funcionando', freq: 'Mensal' },
      { texto: 'Fitas LED funcionando', freq: 'Mensal' },
      { texto: 'Iluminação dos espelhos funcionando', freq: 'Mensal' },
      { texto: 'Iluminação da recepção funcionando', freq: 'Mensal' },
      { texto: 'Iluminação dos lavatórios funcionando', freq: 'Mensal' },
      { texto: 'Iluminação dos banheiros funcionando', freq: 'Mensal' },
      { texto: 'Iluminação externa funcionando', freq: 'Mensal' },
      { texto: 'Fachada iluminada', freq: 'Mensal' },
      { texto: 'Letreiro iluminado', freq: 'Mensal' },
      { texto: 'Sensores funcionando, quando houver', freq: 'Mensal' },
      { texto: 'Temporizadores funcionando, quando houver', freq: 'Mensal' },
      { texto: 'Luminárias firmes', freq: 'Mensal' },
      { texto: 'Sem fios aparentes', freq: 'Mensal' },
    ],
  },
  {
    nome: 'HIDRÁULICA',
    itens: [
      { texto: 'Água — Torneiras funcionando', freq: 'Mensal' },
      { texto: 'Água — Registros funcionando', freq: 'Mensal' },
      { texto: 'Água — Pressão adequada', freq: 'Mensal' },
      { texto: 'Água — Sem vazamentos', freq: 'Mensal' },
      { texto: 'Água — Mangueiras em bom estado', freq: 'Mensal' },
      { texto: 'Água — Conexões sem vazamento', freq: 'Mensal' },
      { texto: 'Água — Tubulações sem vazamento aparente', freq: 'Mensal' },
      { texto: 'Lavatórios — Torneira funcionando', freq: 'Mensal' },
      { texto: 'Lavatórios — Registro funcionando', freq: 'Mensal' },
      { texto: 'Lavatórios — Cuba íntegra', freq: 'Mensal' },
      { texto: 'Lavatórios — Ralo funcionando', freq: 'Mensal' },
      { texto: 'Lavatórios — Sifão sem vazamento', freq: 'Mensal' },
      { texto: 'Lavatórios — Mangueira de ducha funcionando', freq: 'Mensal' },
      { texto: 'Lavatórios — Ducha funcionando', freq: 'Mensal' },
      { texto: 'Lavatórios — Suporte da ducha firme', freq: 'Mensal' },
      { texto: 'Lavatórios — Água quente funcionando, quando houver', freq: 'Mensal' },
      { texto: 'Lavatórios — Misturador funcionando', freq: 'Mensal' },
      { texto: 'Banheiros — Torneira', freq: 'Mensal' },
      { texto: 'Banheiros — Descarga', freq: 'Mensal' },
      { texto: 'Banheiros — Vaso sanitário', freq: 'Mensal' },
      { texto: 'Banheiros — Caixa acoplada', freq: 'Mensal' },
      { texto: 'Banheiros — Sifão', freq: 'Mensal' },
      { texto: 'Banheiros — Ralo', freq: 'Mensal' },
      { texto: 'Banheiros — Registro', freq: 'Mensal' },
      { texto: 'Banheiros — Chuveiro, se houver', freq: 'Mensal' },
      { texto: 'Banheiros — Vazamentos', freq: 'Mensal' },
      { texto: 'Banheiros — Vedação', freq: 'Mensal' },
      { texto: 'Banheiros — Acessórios fixados', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ESGOTO E DRENAGEM',
    itens: [
      { texto: 'Ralos funcionando', freq: 'Mensal' },
      { texto: 'Ralos sem entupimento', freq: 'Mensal' },
      { texto: 'Sifões funcionando', freq: 'Mensal' },
      { texto: 'Tubulações sem vazamentos', freq: 'Mensal' },
      { texto: 'Lavatórios drenando corretamente', freq: 'Mensal' },
      { texto: 'Banheiros drenando corretamente', freq: 'Mensal' },
      { texto: 'Caixa de gordura, quando aplicável', freq: 'Mensal' },
      { texto: 'Grelhas íntegras', freq: 'Mensal' },
      { texto: 'Canaletas funcionando', freq: 'Mensal' },
      { texto: 'Ausência de retorno de esgoto', freq: 'Mensal' },
      { texto: 'Ausência de mau cheiro anormal', freq: 'Mensal' },
      { texto: 'Drenos de equipamentos funcionando', freq: 'Mensal' },
    ],
  },
  {
    nome: 'AR-CONDICIONADO / CLIMATIZAÇÃO',
    itens: [
      { texto: 'Liga', freq: 'Mensal' },
      { texto: 'Desliga', freq: 'Mensal' },
      { texto: 'Resfria adequadamente', freq: 'Mensal' },
      { texto: 'Controle remoto funcionando', freq: 'Mensal' },
      { texto: 'Filtros limpos', freq: 'Mensal' },
      { texto: 'Evaporadora limpa', freq: 'Mensal' },
      { texto: 'Condensadora em condições adequadas', freq: 'Mensal' },
      { texto: 'Dreno desobstruído', freq: 'Mensal' },
      { texto: 'Sem vazamento de água', freq: 'Mensal' },
      { texto: 'Sem ruído anormal', freq: 'Mensal' },
      { texto: 'Sem vibração anormal', freq: 'Mensal' },
      { texto: 'Temperatura adequada', freq: 'Mensal' },
      { texto: 'Tubulação isolada', freq: 'Mensal' },
      { texto: 'Suporte firme', freq: 'Mensal' },
      { texto: 'Instalação elétrica adequada', freq: 'Mensal' },
      { texto: 'Manutenção preventiva registrada', freq: 'Mensal' },
    ],
  },
  {
    nome: 'SEGURANÇA CONTRA INCÊNDIO',
    itens: [
      { texto: 'Extintores presentes', freq: 'Mensal' },
      { texto: 'Extintores acessíveis', freq: 'Mensal' },
      { texto: 'Extintores sinalizados', freq: 'Mensal' },
      { texto: 'Lacres íntegros', freq: 'Mensal' },
      { texto: 'Manômetros em condição adequada, quando aplicável', freq: 'Mensal' },
      { texto: 'Validade/inspeção controlada', freq: 'Mensal' },
      { texto: 'Sinalização de emergência', freq: 'Mensal' },
      { texto: 'Iluminação de emergência', freq: 'Mensal' },
      { texto: 'Saídas desobstruídas', freq: 'Mensal' },
      { texto: 'Portas de emergência funcionando, quando houver', freq: 'Mensal' },
      { texto: 'Rotas de fuga livres', freq: 'Mensal' },
      { texto: 'Placas de emergência íntegras', freq: 'Mensal' },
      { texto: 'Equipamentos de emergência acessíveis', freq: 'Mensal' },
      { texto: 'Documentação aplicável atualizada', freq: 'Mensal' },
    ],
  },
  {
    nome: 'DETECÇÃO E ALARME',
    itens: [
      { texto: 'Central de alarme', freq: 'Mensal' },
      { texto: 'Detectores', freq: 'Mensal' },
      { texto: 'Acionadores manuais', freq: 'Mensal' },
      { texto: 'Sirenes', freq: 'Mensal' },
      { texto: 'Sensores', freq: 'Mensal' },
      { texto: 'Bateria', freq: 'Mensal' },
      { texto: 'Cabeamento', freq: 'Mensal' },
      { texto: 'Comunicação do sistema', freq: 'Mensal' },
      { texto: 'Teste periódico registrado', freq: 'Mensal' },
    ],
  },
  {
    nome: 'SEGURANÇA ELETRÔNICA',
    itens: [
      { texto: 'CFTV — Câmeras funcionando', freq: 'Mensal' },
      { texto: 'CFTV — Imagens nítidas', freq: 'Mensal' },
      { texto: 'CFTV — Câmeras posicionadas corretamente', freq: 'Mensal' },
      { texto: 'CFTV — Gravador funcionando', freq: 'Mensal' },
      { texto: 'CFTV — Armazenamento funcionando', freq: 'Mensal' },
      { texto: 'CFTV — Data/hora corretas', freq: 'Mensal' },
      { texto: 'CFTV — Monitor funcionando', freq: 'Mensal' },
      { texto: 'CFTV — Acesso ao sistema funcionando', freq: 'Mensal' },
      { texto: 'Alarme — Central funcionando', freq: 'Mensal' },
      { texto: 'Alarme — Sensores funcionando', freq: 'Mensal' },
      { texto: 'Alarme — Sirene funcionando', freq: 'Mensal' },
      { texto: 'Alarme — Controle remoto funcionando', freq: 'Mensal' },
      { texto: 'Alarme — Bateria funcionando', freq: 'Mensal' },
      { texto: 'Alarme — Comunicação funcionando', freq: 'Mensal' },
    ],
  },
  {
    nome: 'INTERNET / INFRAESTRUTURA DE REDE',
    itens: [
      { texto: 'Roteador funcionando', freq: 'Mensal' },
      { texto: 'Modem funcionando', freq: 'Mensal' },
      { texto: 'Switch funcionando', freq: 'Mensal' },
      { texto: 'Pontos de rede funcionando', freq: 'Mensal' },
      { texto: 'Cabos organizados', freq: 'Mensal' },
      { texto: 'Cabos sem danos', freq: 'Mensal' },
      { texto: 'Rack organizado, quando houver', freq: 'Mensal' },
      { texto: 'Equipamentos ventilados', freq: 'Mensal' },
      { texto: 'Nobreak funcionando, quando houver', freq: 'Mensal' },
      { texto: 'Tomadas do rack funcionando', freq: 'Mensal' },
    ],
  },
  {
    nome: 'MOBILIÁRIO DO SALÃO',
    itens: [
      { texto: 'Cadeiras de corte — Estrutura firme', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Base firme', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Sistema hidráulico funcionando', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Regulagem funcionando', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Encosto funcionando', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Apoio de braço íntegro', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Estofamento íntegro', freq: 'Mensal' },
      { texto: 'Cadeiras de corte — Rodízios funcionando', freq: 'Mensal' },
      { texto: 'Cadeiras de manicure — Estrutura firme', freq: 'Mensal' },
      { texto: 'Cadeiras de manicure — Regulagens funcionando', freq: 'Mensal' },
      { texto: 'Cadeiras de manicure — Rodízios funcionando', freq: 'Mensal' },
      { texto: 'Cadeiras de manicure — Estofamento íntegro', freq: 'Mensal' },
      { texto: 'Poltronas / recepção — Estrutura firme', freq: 'Mensal' },
      { texto: 'Poltronas / recepção — Pés firmes', freq: 'Mensal' },
      { texto: 'Poltronas / recepção — Estofamento', freq: 'Mensal' },
      { texto: 'Poltronas / recepção — Costuras', freq: 'Mensal' },
      { texto: 'Poltronas / recepção — Apoios', freq: 'Mensal' },
      { texto: 'Poltronas / recepção — Rodízios', freq: 'Mensal' },
      { texto: 'Carrinhos auxiliares — Rodas', freq: 'Mensal' },
      { texto: 'Carrinhos auxiliares — Gavetas', freq: 'Mensal' },
      { texto: 'Carrinhos auxiliares — Estrutura', freq: 'Mensal' },
      { texto: 'Carrinhos auxiliares — Bandejas', freq: 'Mensal' },
      { texto: 'Carrinhos auxiliares — Rodízios', freq: 'Mensal' },
      { texto: 'Armários — Portas', freq: 'Mensal' },
      { texto: 'Armários — Dobradiças', freq: 'Mensal' },
      { texto: 'Armários — Fechaduras', freq: 'Mensal' },
      { texto: 'Armários — Gavetas', freq: 'Mensal' },
      { texto: 'Armários — Corrediças', freq: 'Mensal' },
      { texto: 'Armários — Puxadores', freq: 'Mensal' },
      { texto: 'Armários — Estrutura', freq: 'Mensal' },
    ],
  },
  {
    nome: 'EQUIPAMENTOS DE CABELEIREIRO',
    itens: [
      { texto: 'Secadores — Liga', freq: 'Mensal' },
      { texto: 'Secadores — Desliga', freq: 'Mensal' },
      { texto: 'Secadores — Temperaturas funcionando', freq: 'Mensal' },
      { texto: 'Secadores — Velocidades funcionando', freq: 'Mensal' },
      { texto: 'Secadores — Cabo íntegro', freq: 'Mensal' },
      { texto: 'Secadores — Plugue íntegro', freq: 'Mensal' },
      { texto: 'Secadores — Sem aquecimento anormal', freq: 'Mensal' },
      { texto: 'Secadores — Filtro/entrada de ar limpo', freq: 'Mensal' },
      { texto: 'Secadores — Sem ruído anormal', freq: 'Mensal' },
      { texto: 'Pranchas — Liga', freq: 'Mensal' },
      { texto: 'Pranchas — Temperatura funcionando', freq: 'Mensal' },
      { texto: 'Pranchas — Cabo íntegro', freq: 'Mensal' },
      { texto: 'Pranchas — Plugue íntegro', freq: 'Mensal' },
      { texto: 'Pranchas — Placas íntegras', freq: 'Mensal' },
      { texto: 'Pranchas — Controle funcionando', freq: 'Mensal' },
      { texto: 'Pranchas — Sem aquecimento anormal', freq: 'Mensal' },
      { texto: 'Modeladores/Babyliss — Liga', freq: 'Mensal' },
      { texto: 'Modeladores/Babyliss — Temperatura', freq: 'Mensal' },
      { texto: 'Modeladores/Babyliss — Cabo', freq: 'Mensal' },
      { texto: 'Modeladores/Babyliss — Plugue', freq: 'Mensal' },
      { texto: 'Modeladores/Babyliss — Estrutura', freq: 'Mensal' },
      { texto: 'Modeladores/Babyliss — Controle', freq: 'Mensal' },
      { texto: 'Máquinas de corte — Motor', freq: 'Mensal' },
      { texto: 'Máquinas de corte — Lâminas', freq: 'Mensal' },
      { texto: 'Máquinas de corte — Cabo', freq: 'Mensal' },
      { texto: 'Máquinas de corte — Bateria', freq: 'Mensal' },
      { texto: 'Máquinas de corte — Carregador', freq: 'Mensal' },
      { texto: 'Máquinas de corte — Ruído', freq: 'Mensal' },
      { texto: 'Máquinas de corte — Lubrificação conforme fabricante', freq: 'Mensal' },
    ],
  },
  {
    nome: 'EQUIPAMENTOS DOS LAVATÓRIOS',
    itens: [
      { texto: 'Lavatório', freq: 'Mensal' },
      { texto: 'Cuba', freq: 'Mensal' },
      { texto: 'Torneira', freq: 'Mensal' },
      { texto: 'Misturador', freq: 'Mensal' },
      { texto: 'Ducha', freq: 'Mensal' },
      { texto: 'Mangueira', freq: 'Mensal' },
      { texto: 'Sifão', freq: 'Mensal' },
      { texto: 'Dreno', freq: 'Mensal' },
      { texto: 'Aquecedor, quando houver', freq: 'Mensal' },
      { texto: 'Sistema de água quente', freq: 'Mensal' },
      { texto: 'Estrutura da cadeira', freq: 'Mensal' },
      { texto: 'Estofamento', freq: 'Mensal' },
      { texto: 'Regulagem', freq: 'Mensal' },
      { texto: 'Apoio de pescoço', freq: 'Mensal' },
      { texto: 'Vedação', freq: 'Mensal' },
    ],
  },
  {
    nome: 'EQUIPAMENTOS DE MANICURE / PEDICURE',
    itens: [
      { texto: 'Cadeiras', freq: 'Mensal' },
      { texto: 'Mesas', freq: 'Mensal' },
      { texto: 'Luminárias', freq: 'Mensal' },
      { texto: 'Cabos elétricos', freq: 'Mensal' },
      { texto: 'Lixas elétricas', freq: 'Mensal' },
      { texto: 'Micromotores', freq: 'Mensal' },
      { texto: 'Cabines UV/LED', freq: 'Mensal' },
      { texto: 'Equipamentos de esterilização, conforme estrutura do salão', freq: 'Mensal' },
      { texto: 'Pedilúvios', freq: 'Mensal' },
      { texto: 'Hidromassagem', freq: 'Mensal' },
      { texto: 'Aquecedores', freq: 'Mensal' },
      { texto: 'Sistemas de drenagem', freq: 'Mensal' },
      { texto: 'Apoios', freq: 'Mensal' },
      { texto: 'Pedaleiras', freq: 'Mensal' },
    ],
  },
  {
    nome: 'EQUIPAMENTOS DE ESTÉTICA',
    itens: [
      { texto: 'Macas', freq: 'Mensal' },
      { texto: 'Carrinhos', freq: 'Mensal' },
      { texto: 'Vaporizadores', freq: 'Mensal' },
      { texto: 'Alta frequência', freq: 'Mensal' },
      { texto: 'Aparelhos de radiofrequência', freq: 'Mensal' },
      { texto: 'Ultrassom', freq: 'Mensal' },
      { texto: 'Equipamentos de limpeza de pele', freq: 'Mensal' },
      { texto: 'Equipamentos de LED', freq: 'Mensal' },
      { texto: 'Outros equipamentos estéticos', freq: 'Mensal' },
      { texto: 'Cabos', freq: 'Mensal' },
      { texto: 'Fontes', freq: 'Mensal' },
      { texto: 'Pedais', freq: 'Mensal' },
      { texto: 'Acessórios', freq: 'Mensal' },
      { texto: 'Manutenção preventiva', freq: 'Mensal' },
      { texto: 'Registro de manutenção', freq: 'Mensal' },
    ],
  },
  {
    nome: 'LAVANDERIA',
    itens: [
      { texto: 'Máquina de lavar — Funcionamento', freq: 'Mensal' },
      { texto: 'Máquina de lavar — Mangueiras', freq: 'Mensal' },
      { texto: 'Máquina de lavar — Entrada de água', freq: 'Mensal' },
      { texto: 'Máquina de lavar — Saída de água', freq: 'Mensal' },
      { texto: 'Máquina de lavar — Drenagem', freq: 'Mensal' },
      { texto: 'Máquina de lavar — Vazamentos', freq: 'Mensal' },
      { texto: 'Máquina de lavar — Borracha de vedação', freq: 'Mensal' },
      { texto: 'Máquina de lavar — Filtro', freq: 'Mensal' },
      { texto: 'Máquina de lavar — Ruídos', freq: 'Mensal' },
      { texto: 'Máquina de lavar — Vibração', freq: 'Mensal' },
      { texto: 'Secadora — Funcionamento', freq: 'Mensal' },
      { texto: 'Secadora — Filtro', freq: 'Mensal' },
      { texto: 'Secadora — Ventilação', freq: 'Mensal' },
      { texto: 'Secadora — Duto', freq: 'Mensal' },
      { texto: 'Secadora — Cabo', freq: 'Mensal' },
      { texto: 'Secadora — Plugue', freq: 'Mensal' },
      { texto: 'Secadora — Aquecimento adequado', freq: 'Mensal' },
    ],
  },
  {
    nome: 'EQUIPAMENTOS DE LIMPEZA',
    itens: [
      { texto: 'Aspirador', freq: 'Mensal' },
      { texto: 'Lavadora', freq: 'Mensal' },
      { texto: 'Enceradeira, se houver', freq: 'Mensal' },
      { texto: 'Extratora, se houver', freq: 'Mensal' },
      { texto: 'Vassouras elétricas, se houver', freq: 'Mensal' },
      { texto: 'Cabos', freq: 'Mensal' },
      { texto: 'Tomadas', freq: 'Mensal' },
      { texto: 'Filtros', freq: 'Mensal' },
      { texto: 'Mangueiras', freq: 'Mensal' },
      { texto: 'Rodas', freq: 'Mensal' },
      { texto: 'Reservatórios', freq: 'Mensal' },
      { texto: 'Baterias/carregadores', freq: 'Mensal' },
    ],
  },
  {
    nome: 'COPA / ÁREA DE APOIO',
    itens: [
      { texto: 'Geladeira', freq: 'Mensal' },
      { texto: 'Freezer', freq: 'Mensal' },
      { texto: 'Micro-ondas', freq: 'Mensal' },
      { texto: 'Cafeteira', freq: 'Mensal' },
      { texto: 'Purificador', freq: 'Mensal' },
      { texto: 'Filtro de água', freq: 'Mensal' },
      { texto: 'Bebedouro', freq: 'Mensal' },
      { texto: 'Forno', freq: 'Mensal' },
      { texto: 'Armários', freq: 'Mensal' },
      { texto: 'Torneira', freq: 'Mensal' },
      { texto: 'Pia', freq: 'Mensal' },
      { texto: 'Sifão', freq: 'Mensal' },
      { texto: 'Tomadas', freq: 'Mensal' },
      { texto: 'Instalação elétrica', freq: 'Mensal' },
    ],
  },
  {
    nome: 'BEBEDOURO / PURIFICADOR',
    itens: [
      { texto: 'Funcionamento', freq: 'Mensal' },
      { texto: 'Vazamento', freq: 'Mensal' },
      { texto: 'Torneira', freq: 'Mensal' },
      { texto: 'Mangueira', freq: 'Mensal' },
      { texto: 'Filtro', freq: 'Mensal' },
      { texto: 'Prazo de troca do filtro', freq: 'Mensal' },
      { texto: 'Refrigeração, quando houver', freq: 'Mensal' },
      { texto: 'Limpeza técnica', freq: 'Mensal' },
      { texto: 'Manutenção registrada', freq: 'Mensal' },
    ],
  },
  {
    nome: 'FACHADA E ÁREA EXTERNA',
    itens: [
      { texto: 'Letreiro', freq: 'Mensal' },
      { texto: 'Iluminação da fachada', freq: 'Mensal' },
      { texto: 'Placa', freq: 'Mensal' },
      { texto: 'Revestimento', freq: 'Mensal' },
      { texto: 'Pintura', freq: 'Mensal' },
      { texto: 'Vidros', freq: 'Mensal' },
      { texto: 'Porta de entrada', freq: 'Mensal' },
      { texto: 'Fechadura', freq: 'Mensal' },
      { texto: 'Calçada', freq: 'Mensal' },
      { texto: 'Marquise', freq: 'Mensal' },
      { texto: 'Toldos', freq: 'Mensal' },
      { texto: 'Estruturas externas', freq: 'Mensal' },
      { texto: 'Comunicação visual', freq: 'Mensal' },
      { texto: 'Elementos decorativos externos', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ELEVADOR / PLATAFORMAS',
    itens: [
      { texto: 'Funcionamento', freq: 'Mensal' },
      { texto: 'Portas', freq: 'Mensal' },
      { texto: 'Botões', freq: 'Mensal' },
      { texto: 'Iluminação', freq: 'Mensal' },
      { texto: 'Comunicação', freq: 'Mensal' },
      { texto: 'Alarmes', freq: 'Mensal' },
      { texto: 'Manutenção contratada', freq: 'Mensal' },
      { texto: 'Inspeções obrigatórias', freq: 'Mensal' },
      { texto: 'Registros de manutenção', freq: 'Mensal' },
    ],
  },
  {
    nome: 'ESTACIONAMENTO / ACESSO',
    itens: [
      { texto: 'Iluminação', freq: 'Mensal' },
      { texto: 'Portões', freq: 'Mensal' },
      { texto: 'Motor do portão', freq: 'Mensal' },
      { texto: 'Controle remoto', freq: 'Mensal' },
      { texto: 'Interfone', freq: 'Mensal' },
      { texto: 'Câmeras', freq: 'Mensal' },
      { texto: 'Sinalização', freq: 'Mensal' },
      { texto: 'Piso', freq: 'Mensal' },
      { texto: 'Drenagem', freq: 'Mensal' },
      { texto: 'Estrutura', freq: 'Mensal' },
    ],
  },
  {
    nome: 'FECHADURAS E CONTROLE DE ACESSO',
    itens: [
      { texto: 'Fechaduras', freq: 'Mensal' },
      { texto: 'Maçanetas', freq: 'Mensal' },
      { texto: 'Chaves', freq: 'Mensal' },
      { texto: 'Controle eletrônico', freq: 'Mensal' },
      { texto: 'Fechaduras digitais', freq: 'Mensal' },
      { texto: 'Senhas', freq: 'Mensal' },
      { texto: 'Biometria', freq: 'Mensal' },
      { texto: 'Leitores', freq: 'Mensal' },
      { texto: 'Portões', freq: 'Mensal' },
      { texto: 'Interfone', freq: 'Mensal' },
      { texto: 'Campainha', freq: 'Mensal' },
    ],
  },
  {
    nome: 'NOBREAK / GERADOR',
    itens: [
      { texto: 'Nobreak — Nobreak funcionando', freq: 'Mensal' },
      { texto: 'Nobreak — Bateria', freq: 'Mensal' },
      { texto: 'Nobreak — Autonomia', freq: 'Mensal' },
      { texto: 'Nobreak — Cabos', freq: 'Mensal' },
      { texto: 'Nobreak — Tomadas', freq: 'Mensal' },
      { texto: 'Nobreak — Indicadores', freq: 'Mensal' },
      { texto: 'Nobreak — Teste periódico', freq: 'Mensal' },
      { texto: 'Gerador — Combustível', freq: 'Mensal' },
      { texto: 'Gerador — Bateria', freq: 'Mensal' },
      { texto: 'Gerador — Motor', freq: 'Mensal' },
      { texto: 'Gerador — Cabos', freq: 'Mensal' },
      { texto: 'Gerador — Sistema de acionamento', freq: 'Mensal' },
      { texto: 'Gerador — Teste', freq: 'Mensal' },
      { texto: 'Gerador — Manutenção preventiva', freq: 'Mensal' },
    ],
  },
  {
    nome: 'EQUIPAMENTOS DE EMERGÊNCIA',
    itens: [
      { texto: 'Kit primeiros socorros', freq: 'Mensal' },
      { texto: 'Iluminação de emergência', freq: 'Mensal' },
      { texto: 'Sinalização', freq: 'Mensal' },
      { texto: 'Extintores', freq: 'Mensal' },
      { texto: 'Alarmes', freq: 'Mensal' },
      { texto: 'Rotas de fuga', freq: 'Mensal' },
      { texto: 'Saídas', freq: 'Mensal' },
      { texto: 'Equipamentos de emergência', freq: 'Mensal' },
      { texto: 'Telefones de emergência disponíveis', freq: 'Mensal' },
    ],
  },
  {
    nome: 'FERRAMENTAS DA MANUTENÇÃO',
    itens: [
      { texto: 'Ferramentas identificadas', freq: 'Mensal' },
      { texto: 'Ferramentas organizadas', freq: 'Mensal' },
      { texto: 'Ferramentas em bom estado', freq: 'Mensal' },
      { texto: 'Ferramentas elétricas em bom estado', freq: 'Mensal' },
      { texto: 'Cabos íntegros', freq: 'Mensal' },
      { texto: 'Equipamentos de proteção', freq: 'Mensal' },
      { texto: 'Local de armazenamento adequado', freq: 'Mensal' },
    ],
  },
]
