// Padrões de fábrica da configuração remota dos programas desktop (Suite NODRI).
// Mesmos valores embutidos nos .py — o painel usa como referência/placeholder.
export const PROGRAMAS_DEFAULTS = {
  listas_foto: {
    xpath_anexo: '//*[@id="main"]/footer/div[1]/div/span/div/div/div/div[1]/div/span/button/div/div/div[1]/span',
    xpath_imagem: '//*[@id="app"]/div/div/span[6]/div/ul/div/div/div[2]/li/div/span',
  },
  confirmacao_feedback: {
    relatorio_url: 'https://admin.avec.beauty/admin/relatorio/0051',
    xpath_login_email: '//*[@id="single-spa-application:@hyperlocal/auth"]/div/div/div/div[2]/div[2]/div[1]/div[2]/div/input',
    xpath_login_senha: '//*[@id="single-spa-application:@hyperlocal/auth"]/div/div/div/div[2]/div[2]/div[1]/div[3]/div/input',
    xpath_login_botao: '//*[@id="single-spa-application:@hyperlocal/auth"]/div/div/div/div[2]/div[2]/div[2]/div/button[1]',
    xpath_data_inicio: '//*[@id="variaveis"]/div[1]/span[1]/div/input',
    xpath_data_fim: '//*[@id="variaveis"]/div[1]/span[2]/div/input',
    xpath_btn_buscar: '//*[@id="variaveis"]/div[1]/span[5]/button',
    xpath_btn_excel: '//*[@id="tableFilter_wrapper"]/div[3]/a[2]/span',
    tempo_pagina: 15,
    tempo_apos_senha: 4,
    tempo_apos_login: 15,
    tempo_apos_relatorio: 15,
    tempo_apos_busca: 5,
    tempo_apos_exportar: 5,
  },
  relatorio: {
    timeout_login: 30,
    timeout_pagina: 120,
    timeout_elemento: 30,
    timeout_download: 20,
    timeout_pausa_buscar: 30,
    xpath_login_email: "//*[@id='single-spa-application:@hyperlocal/auth']/div/div/div/div[2]/div[2]/div[1]/div[2]/div/input",
    xpath_login_senha: "//*[@id='single-spa-application:@hyperlocal/auth']/div/div/div/div[2]/div[2]/div[1]/div[3]/div/input",
    xpath_login_botao: "//*[@id='single-spa-application:@hyperlocal/auth']/div/div/div/div[2]/div[2]/div[2]/div/button[1]",
    xpath_data_inicio: "//*[@id='variaveis']/div[1]/span[1]/div/input",
    xpath_data_fim: "//*[@id='variaveis']/div[1]/span[2]/div/input",
    xpath_btn_buscar: "//*[@id='variaveis']/div[1]/span[3]/button",
    xpath_btn_buscar_0021: "//*[@id='variaveis']/div[1]/span[4]/button",
    xpath_btn_buscar_0126: "//*[@id='variaveis']/div[1]/span[4]/button",
    xpath_btn_excel: "//*[@id='tableFilter_wrapper']/div[3]/a[2]/span",
    xpath_btn_excel_0021: "//*[@id='tableFilter_wrapper']/div[3]/a[2]",
    xpath_btn_excel_0126: "//*[@id='tableFilter_wrapper']/div[3]/a[2]",
    url_0083: 'https://admin.avec.beauty/admin/relatorio/0083',
    url_0017: 'https://admin.avec.beauty/admin/relatorio/0017',
    url_0032: 'https://admin.avec.beauty/admin/relatorio/0032',
    url_0042: 'https://admin.avec.beauty/admin/relatorio/0042',
    url_0088: 'https://admin.avec.beauty/admin/relatorio/0088',
    url_0123: 'https://admin.avec.beauty/admin/relatorio/0123',
    url_0021: 'https://admin.avec.beauty/admin/relatorio/0021',
    url_0326: 'https://admin.avec.beauty/admin/relatorio/0326',
    url_0126: 'https://admin.avec.beauty/admin/relatorio/0126',
    url_0031: 'https://admin.avec.beauty/admin/relatorio/0031',
    url_0041: 'https://admin.avec.beauty/admin/relatorio/0041',
    url_0051: 'https://admin.avec.beauty/admin/relatorio/0051',
  },
}
