// Categorias e demandas padrão do Check List (editáveis pelo usuário)
export const CHECKLIST_DEFAULT: { nome: string; demandas: string[] }[] = [
  {
    nome: 'Abertura', demandas: [
      'Agendamentos Grandes ou Múltiplos - Verificar e organizar',
      'Agendas - Verificar todos os agendamentos para ver se estão corretos',
      'Colocar o bolo da Ivone na vitrine',
      'Colocar o feedback sobre tudo o que aconteceu no salão na planilha de feedback às 15:30',
      'Dar entrada em todos os produtos que chegaram',
      'Descer o toldo',
      'Distribuir os clientes não preferenciais',
      'Escala de Domingo - Organizar as agendas conforme a escala',
      'Escala de Domingo - Verificar se há profissionais suficientes para a demanda. Caso não, falar com o gerente',
      'Ligar os aparelhos de ar condicionado: apenas na área central do salão às 08:30 (ou nas salas específicas, caso estejam em uso)',
      'Ligar todas as luzes dos espelhos',
      'Ligar todos os computadores às 08:00',
      'Limpeza e organização das vitrines e ordenar por datas de vencimento (o mais recente na frente) e ver se todos os produtos estão com o preço',
      'Organizar o salão, cadeiras, bancadas, carrinhos',
      'Responder a todas as mensagens no WhatsApp e ver se tem mensagem do início, meio e fim do dia, clicado mas sem responder',
      'Fechar o caixa às 15:00',
      'Ver se os bloqueios de serviços internos estão certos',
      'Ver se está tendo desfalque de profissional no dia a dia ou nos domingos e organizar',
      'Pegar as cartas que ficam no armário do correio e colocar na pasta de contas na recepção',
    ]
  },
  {
    nome: 'Intermediário', demandas: [
      'Atualizar todas as listas (CORTE / PIGMENTAÇÃO / REALINHAMENTO / MECHAS / CAFÉ)',
      'Colocar o feedback sobre tudo o que aconteceu no salão na planilha de feedback às 18:30',
      'Confirmação dos agendamentos do dia seguinte às 17:00',
      'Dar entrada em todos os produtos que chegaram',
      'Distribuir os clientes não preferenciais',
      'Envio das listas promocionais',
      'Escala de Domingo - Organizar as agendas conforme a escala',
      'Escala de Domingo - Verificar se há profissionais suficientes para a demanda. Caso não, falar com o gerente',
      'Instagram - verificar se tem mensagens, se tiver responder',
      'Ligar o letreiro da fachada',
      'Limpeza e organização das vitrines e ordenar por datas de vencimento (o mais recente na frente) e ver se todos os produtos estão com o preço',
      'Organizar o salão, cadeiras, bancadas, carrinhos',
      'Responder a todas as mensagens no WhatsApp e ver se tem mensagem do início, meio e fim do dia, clicado mas sem responder',
      'Verificar todas as comandas que estão em aberto no sistema e fechar',
      'Até as 11:00 - Execução [Envio das listas promocionais]',
      'Fechar o caixa às 18:00',
      'Subir o toldo',
    ]
  },
  {
    nome: 'Fechamento', demandas: [
      'Verificar no relatório 017 todos os clientes novos se está preenchido como conheceu o salão; se não tiver, encaminhar uma mensagem',
      'Colocar o feedback sobre tudo o que aconteceu no salão na planilha de feedback às 20:50',
      'Dar entrada em todos os produtos que chegaram',
      'Desligar o letreiro da fachada',
      'Distribuir os clientes não preferenciais',
      'Emitir todas as notas fiscais pendentes',
      'Escala de Domingo - Organizar as agendas conforme a escala',
      'Escala de Domingo - Verificar se há profissionais suficientes para a demanda. Caso não, falar com o gerente',
      'Ligar o letreiro da fachada',
      'Limpeza e organização das vitrines e ordenar por datas de vencimento (o mais recente na frente) e ver se todos os produtos estão com o preço',
      'Organizar o salão, cadeiras, bancadas, carrinhos',
      'Responder a todas as mensagens no WhatsApp e ver se tem mensagem do início, meio e fim do dia, clicado mas sem responder',
      'Verificar se tem profissional suficiente para o dia seguinte',
      'Até as 15:00 - Execução [Organizar a agenda do dia seguinte (sem preferência)]',
      'Enviar mensagem de feedback',
      'Fechar o caixa às 20:50',
      'Lançar todos os boletos na planilha de custo, depois deixar na mesa da Bruna',
    ]
  },
  {
    nome: 'Manutenção / Limpeza', demandas: [
      'Limpeza constante da máquina de café',
      'Abastecer a máquina com água',
      'Abastecer a máquina de café com grãos',
      'Banheiro - lavar espelho',
      'Banheiro - passar cheirinho',
      'Banheiro - repor sabonete',
      'Colocar na área externa as cadeiras laranja pela manhã',
      'Deixar o espaço do café limpo e organizado',
      'Lavar o banheiro 2x ao dia às 08:00 e 15:30',
      'Lavatórios - Limpo',
      'Limpar micro-ondas por dentro e por fora 1x ao dia',
      'Limpar os lavatórios e suporte onde retêm os cabelos',
      'Limpeza constante da área central e atendimento do salão',
      'Limpeza constante das bancadas e cadeiras de atendimento',
      'Limpeza da pia e cantos',
      'Limpeza das paredes do salão',
      'Limpeza de todos os cantinhos do salão',
      'Limpeza diária das lixeiras dentro e fora',
      'Limpeza do vaso sanitário',
      'Limpeza do teto do salão',
      'Limpeza do vidro da recepção',
      'Limpeza dos rodapés do salão',
      'Limpeza dos espelhos das escadas',
      'Limpeza dos espelhos do jardim',
      'Limpeza dos espelhos das bancadas',
      'Limpeza dos vidros da entrada principal do salão',
      'Organização semanal do estoque de produtos',
      'Remoção de manchas das cadeiras e poltronas',
      'Reposição de papel higiênico',
      'Reposição de papel toalha',
      'Retirar os lixos no início e fim do expediente',
      'Subir todos os copos e xícaras',
      'Fazer o pedido de compras de produtos de limpeza',
    ]
  },
  {
    nome: 'Dosagem', demandas: [
      'Lançar todos os serviços internos na folha de controle',
      'Lançar todos os alicates que entraram e saíram com assinaturas do profissional na folha de controle',
      'Esterilizar todos os alicates de unhas',
      'Etiquetar todos os produtos (vermelho / verde / amarelo) com base nas datas de validade',
      'Contar as toalhas sujas para envio para a lavanderia',
      'Dar entrada e saída nos enxovais de lavanderia na planilha',
      'Organizar o estoque de toalhas',
      'Reabastecer os enxovais da lavanderia na dosagem',
      'Fazer o pedido de compras da dosagem',
    ]
  },
  {
    nome: 'Gerente', demandas: [
      'Atraso - Alinhar com todos no dia',
      'Verificar todos os dias a planilha de feedback profissional',
      'Verificar todos os dias a planilha de feedback cliente',
      'Comunicação dos profissionais - Alinhar com todos no dia',
      'Enviar mensagem de feliz aniversário para todos os clientes do mês',
      'Verificar com o gerente o dia do aniversariante do mês',
      'Verificar com a Dosadora o que precisa comprar e o que precisa ser ajustado',
      'Verificar ações comerciais e relembrar os profissionais',
      'Verificar no calendário da planilha central se tem alguma data de algum evento e repassar para a equipe (lembrete)',
      'Imprimir conta de água, luz, lavanderia, conta TIM, Grancoff, telefone fixo e deixar na pasta de contas da recepção para lançamento na planilha de custo',
      'Mandar toda segunda o feedback positivo e negativo no grupo',
      'Verificar se a recepção precisa de algo',
      'Verificar se tem água no reservatório',
      'Enviar os feedbacks no grupo',
      'Escala de Domingo - Ajustar desfalques com outro profissional, se necessário',
      'Café - verificar se comprar algo',
      'Faltas - Alinhar com todos no dia',
      'Fechar a agenda no dia do aniversariante do mês em 30 minutos',
      'Ver feedback e presencial sobre quem faltou, atrasou, motivos e feedbacks de cliente',
      'Verificar se a dosagem precisa de algo',
      'Verificar a limpeza do salão: pegar o check list da limpeza e verificar, passar o fino',
      'Lembrar a Bruna sobre o bolo do aniversariante do mês',
      'Imprimir guias do MEI',
      'Lançar guias do MEI',
      'Ver se as vitrines estão limpas e alinhadas',
      'Verificar o e-mail dos check lists feitos',
      'Verificar a planilha de feedback dos profissionais',
      'Enviar todo dia a dica do dia',
      'Ver todos os boletos em aberto e na pasta transparente',
      'Ver com a Dariana sobre os problemas, se tem algum',
      'Ver com a recepção e limpeza se precisa de algo',
      'Ver imagem pessoal de todos',
      'Atualizar e enviar as corridas',
      'Ver como estão sendo as conversas do zap',
      'Enviar os relatórios gerais do dia no grupo Vera',
      'Verificar o check list da limpeza do salão',
      'Lista de alicates para a dosagem',
      'Lista de café',
      'Lista de complemento para a dosagem',
      'Lista de corte',
      'Lista de mechas',
      'Lista de pigmentação',
      'Lista de realinhamento',
      'Lista de serviços internos para a dosagem',
      'Realizar as demandas / recolhimento de demandas dos profissionais (financeiro, ajustes ou lançamentos incorretos, compra de produtos, ideias de ação)',
      'Verificar se tudo que os profissionais compraram foi lançado',
    ]
  },
  { nome: 'Coordenado', demandas: [] },
  { nome: 'Padrão de Atendimento', demandas: [] },
]

export const FREQUENCIAS = ['Diário', 'Semanal', 'Quinzenal', 'Mensal', 'Trimestral', 'Semestral', 'Anual']
